// Minimal static server for the converged agentos wasm browser test.
// Serves this dir + the built agentos wasm-web package at /wasm/, with COOP/COEP
// (harmless; enables SharedArrayBuffer if later needed) and wasm MIME.

import { createReadStream, existsSync, statSync } from "node:fs";
import { createServer } from "node:http";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(here, "..", "..");
const wasmDir = path.join(packageRoot, ".cache", "agentos-sidecar-wasm-web");
const port = Number(process.env.PORT ?? 43175);

const MIME = {
	".html": "text/html; charset=utf-8",
	".js": "text/javascript; charset=utf-8",
	".mjs": "text/javascript; charset=utf-8",
	".cjs": "text/javascript; charset=utf-8",
	".wasm": "application/wasm",
	".json": "application/json; charset=utf-8",
};

function resolve(urlPath) {
	if (urlPath.startsWith("/wasm/")) {
		return path.join(wasmDir, urlPath.slice("/wasm/".length));
	}
	const rel = urlPath === "/" ? "/index.html" : urlPath;
	return path.join(here, rel);
}

// A mock chrome-llm model server: answers Anthropic /v1/messages with a streaming SSE
// reply carrying a fixed sentinel, so the in-browser pi can complete a session/prompt
// turn (its pi-ai SDK fetches this endpoint as ANTHROPIC_BASE_URL). Stands in for the
// in-sandbox proxy guest + chrome-llm host-callback (mechanism proven by async-proxy).
const PI_SENTINEL = "PONG_FROM_PI_IN_BROWSER";
// Derive a reply from the Anthropic request body. The pi-prompt CI gate sends "Say PONG"
// and asserts the sentinel; the interactive demo sends arbitrary prompts and gets a
// contextual mock answer so the full round-trip is visible.
function mockReplyFor(requestBody) {
	let text = "";
	try {
		const parsed = JSON.parse(requestBody);
		const messages = Array.isArray(parsed.messages) ? parsed.messages : [];
		for (let i = messages.length - 1; i >= 0; i -= 1) {
			if (messages[i].role !== "user") continue;
			const content = messages[i].content;
			text = typeof content === "string"
				? content
				: (Array.isArray(content) ? content.map((p) => (p && p.text) || "").join("") : "");
			break;
		}
	} catch {}
	const q = text.toLowerCase();
	if (/\bpong\b/.test(q)) return PI_SENTINEL;
	if (/2\s*\+\s*2|two plus two/.test(q)) return "2 + 2 = 4.";
	if (/capital of france/.test(q)) return "The capital of France is Paris.";
	if (/who are you|what are you/.test(q)) return "I'm pi, an AI coding agent running entirely inside your browser via agentos, answering through Chrome's on-device model.";
	const clean = text.trim().slice(0, 200);
	return clean
		? `You asked: "${clean}". This reply was generated by pi running in the browser, through the on-device model.`
		: PI_SENTINEL;
}
function anthropicSse(text) {
	const ev = (event, data) => `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
	return (
		ev("message_start", { type: "message_start", message: { id: "msg_mock", type: "message", role: "assistant", model: "claude-mock", content: [], stop_reason: null, stop_sequence: null, usage: { input_tokens: 1, output_tokens: 1 } } }) +
		ev("content_block_start", { type: "content_block_start", index: 0, content_block: { type: "text", text: "" } }) +
		ev("content_block_delta", { type: "content_block_delta", index: 0, delta: { type: "text_delta", text } }) +
		ev("content_block_stop", { type: "content_block_stop", index: 0 }) +
		ev("message_delta", { type: "message_delta", delta: { stop_reason: "end_turn", stop_sequence: null }, usage: { output_tokens: 1 } }) +
		ev("message_stop", { type: "message_stop" })
	);
}

const server = createServer((req, res) => {
	const urlPath = decodeURIComponent((req.url ?? "/").split("?")[0]);
	if (urlPath === "/v1/messages") {
		const corsHeaders = {
			"Access-Control-Allow-Origin": "*",
			"Access-Control-Allow-Methods": "POST, OPTIONS",
			"Access-Control-Allow-Headers": "*",
			"Cross-Origin-Resource-Policy": "cross-origin",
			"Cross-Origin-Embedder-Policy": "require-corp",
		};
		if (req.method === "OPTIONS") {
			res.writeHead(204, corsHeaders).end();
			return;
		}
		let body = "";
		req.on("data", (c) => (body += c));
		req.on("end", () => {
			res.writeHead(200, { ...corsHeaders, "Content-Type": "text/event-stream" }).end(anthropicSse(mockReplyFor(body)));
		});
		return;
	}
	const file = resolve(urlPath);
	if (!file.startsWith(here) && !file.startsWith(wasmDir)) {
		res.writeHead(403).end("forbidden");
		return;
	}
	if (!existsSync(file) || !statSync(file).isFile()) {
		res.writeHead(404).end(`not found: ${urlPath}`);
		return;
	}
	res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
	res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
	res.setHeader("Content-Type", MIME[path.extname(file)] ?? "application/octet-stream");
	createReadStream(file).pipe(res);
});

server.listen(port, () => {
	console.log(`agentos wasm test server on http://localhost:${port} (wasm: ${wasmDir})`);
});
