/* Test whether a basic casinl invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <complex.h>
#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)
#define MF_ANYSIGN1 (1 << 2)
#define MF_ANYSIGN2 (1 << 3)

// Soft fail on rounding errors and report only one.
int imprecise;

void test(int variant, long double complex input1, long double complex lower, long double complex expected, long double complex upper, int flags)
{
	long double complex output = casinl(input1);
	if ( !(flags & MF_UNSPEC1) )
	{
		long double real = creall(output);
		real = (flags & MF_ANYSIGN1) && real < 0.0 ? -real : real;
		long double lower_real = creall(lower);
		long double expected_real = creall(expected);
		long double upper_real = creall(upper);
		if ( !(isnan(expected_real) ? isnan(real) :
		       isfinite(expected_real) && expected_real != 0.0 ?
		       isfinite(real) && (real == expected_real || (lower_real < real && real < upper_real)) :
		       real == expected_real) )
		{
			if ( imprecise && isfinite(real) && isfinite(expected_real) )
				return;
			warnx("(%d.) casinl(%.4Lf + i*%.4Lf).real = %.17La, not %.17La, diff %.17La, ratio %.20Lg",
			     variant, creall(input1), cimagl(input1), real, expected_real,
			     real - expected_real, real / expected_real);
			if ( !isfinite(real) || !isfinite(expected_real) )
				exit(1);
			imprecise = 1;
		}
		long double imag = cimagl(output);
		imag = (flags & MF_ANYSIGN2) && imag < 0.0 ? -imag : imag;
		long double lower_imag = cimagl(lower);
		long double expected_imag = cimagl(expected);
		long double upper_imag = cimagl(upper);
		if ( !(isnan(expected_imag) ? isnan(imag) :
		       isfinite(expected_imag) && expected_imag != 0.0 ?
		       isfinite(imag) && (imag == expected_imag || (lower_imag < imag && imag < upper_imag)) :
		       imag == expected_imag) )
		{
			if ( imprecise && isfinite(imag) && isfinite(expected_imag) )
				return;
			warnx("(%d.) casinl(%.4Lf + i*%.4Lf).imag = %.17La, not %.17La, diff %.17La, ratio %.20Lg",
			     variant, creall(input1), cimagl(input1), imag, expected_imag,
			     imag - expected_imag, imag / expected_imag);
			if ( !isfinite(imag) || !isfinite(expected_imag) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, CMPLXL(0.9001, 0.1337), CMPLXL(0x8.6cb251c1fd0501p-3L, 0x8.8b08affee4ddd41p-5L), CMPLXL(0x8.6cb251c1fd05011p-3L, 0x8.8b08affee4ddd42p-5L), CMPLXL(0x8.6cb251c1fd05012p-3L, 0x8.8b08affee4ddd43p-5L), 0);
	test(2, CMPLXL(-0.1234, 0.1337), CMPLXL(-0xf.b16e38f5b4c177p-7L, 0x8.987c8433f62e8dp-6L), CMPLXL(-0xf.b16e38f5b4c176fp-7L, 0x8.987c8433f62e8d1p-6L), CMPLXL(-0xf.b16e38f5b4c176ep-7L, 0x8.987c8433f62e8d2p-6L), 0);
	test(3, CMPLXL(nanl(""), 0.1337), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(4, CMPLXL(strtold("inf", NULL), 0.1337), CMPLXL(0xc.90fdaa22168c234p-3L, strtold("inf", NULL)), CMPLXL(0xc.90fdaa22168c235p-3L, strtold("inf", NULL)), CMPLXL(0xc.90fdaa22168c236p-3L, strtold("inf", NULL)), 0);
	test(5, CMPLXL(strtold("-inf", NULL), 0.1337), CMPLXL(-0xc.90fdaa22168c236p-3L, strtold("inf", NULL)), CMPLXL(-0xc.90fdaa22168c235p-3L, strtold("inf", NULL)), CMPLXL(-0xc.90fdaa22168c234p-3L, strtold("inf", NULL)), 0);
	test(6, CMPLXL(0.0, 0.1337), CMPLXL(-0x0.000000000000001p-16385L, 0x8.881106a3261170cp-6L), CMPLXL(0x0.0p+0L, 0x8.881106a3261170dp-6L), CMPLXL(0x0.000000000000001p-16385L, 0x8.881106a3261170ep-6L), 0);
	test(7, CMPLXL(0.9001, -0.1234), CMPLXL(0x8.7c2f8130aa750bcp-3L, -0x8.00bd05da044eedcp-5L), CMPLXL(0x8.7c2f8130aa750bdp-3L, -0x8.00bd05da044eedbp-5L), CMPLXL(0x8.7c2f8130aa750bep-3L, -0x8.00bd05da044eedap-5L), 0);
	test(8, CMPLXL(-0.1234, -0.1234), CMPLXL(-0xf.b6c5424add2217p-7L, -0xf.dfcf3b41aa72928p-7L), CMPLXL(-0xf.b6c5424add2216fp-7L, -0xf.dfcf3b41aa72927p-7L), CMPLXL(-0xf.b6c5424add2216ep-7L, -0xf.dfcf3b41aa72926p-7L), 0);
	test(9, CMPLXL(nanl(""), -0.1234), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(10, CMPLXL(strtold("inf", NULL), -0.1234), CMPLXL(0xc.90fdaa22168c234p-3L, strtold("-inf", NULL)), CMPLXL(0xc.90fdaa22168c235p-3L, strtold("-inf", NULL)), CMPLXL(0xc.90fdaa22168c236p-3L, strtold("-inf", NULL)), 0);
	test(11, CMPLXL(strtold("-inf", NULL), -0.1234), CMPLXL(-0xc.90fdaa22168c236p-3L, strtold("-inf", NULL)), CMPLXL(-0xc.90fdaa22168c235p-3L, strtold("-inf", NULL)), CMPLXL(-0xc.90fdaa22168c234p-3L, strtold("-inf", NULL)), 0);
	test(12, CMPLXL(0.0, -0.1234), CMPLXL(-0x0.000000000000001p-16385L, -0xf.c160ec24fa5cbaep-7L), CMPLXL(0x0.0p+0L, -0xf.c160ec24fa5cbadp-7L), CMPLXL(0x0.000000000000001p-16385L, -0xf.c160ec24fa5cbacp-7L), 0);
	test(13, CMPLXL(0.9001, nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(14, CMPLXL(-0.1234, nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(15, CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(16, CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(nanl(""), strtold("inf", NULL)), CMPLXL(nanl(""), strtold("inf", NULL)), CMPLXL(nanl(""), strtold("inf", NULL)), 0 | MF_ANYSIGN2);
	test(17, CMPLXL(strtold("-inf", NULL), nanl("")), CMPLXL(nanl(""), strtold("inf", NULL)), CMPLXL(nanl(""), strtold("inf", NULL)), CMPLXL(nanl(""), strtold("inf", NULL)), 0 | MF_ANYSIGN2);
	test(18, CMPLXL(0.0, nanl("")), CMPLXL(-0x0.000000000000001p-16385L, nanl("")), CMPLXL(0x0.0p+0L, nanl("")), CMPLXL(0x0.000000000000001p-16385L, nanl("")), 0 | MF_ANYSIGN2);
	test(19, CMPLXL(0.9001, strtold("inf", NULL)), CMPLXL(-0x0.000000000000001p-16385L, strtold("inf", NULL)), CMPLXL(0x0.0p+0L, strtold("inf", NULL)), CMPLXL(0x0.000000000000001p-16385L, strtold("inf", NULL)), 0);
	test(20, CMPLXL(-0.1234, strtold("inf", NULL)), CMPLXL(-0x0.000000000000001p-16385L, strtold("inf", NULL)), CMPLXL(-0x0.0p+0L, strtold("inf", NULL)), CMPLXL(0x0.000000000000001p-16385L, strtold("inf", NULL)), 0);
	test(21, CMPLXL(nanl(""), strtold("inf", NULL)), CMPLXL(nanl(""), strtold("inf", NULL)), CMPLXL(nanl(""), strtold("inf", NULL)), CMPLXL(nanl(""), strtold("inf", NULL)), 0);
	test(22, CMPLXL(strtold("inf", NULL), strtold("inf", NULL)), CMPLXL(0xc.90fdaa22168c234p-4L, strtold("inf", NULL)), CMPLXL(0xc.90fdaa22168c235p-4L, strtold("inf", NULL)), CMPLXL(0xc.90fdaa22168c236p-4L, strtold("inf", NULL)), 0);
	test(23, CMPLXL(strtold("-inf", NULL), strtold("inf", NULL)), CMPLXL(-0xc.90fdaa22168c236p-4L, strtold("inf", NULL)), CMPLXL(-0xc.90fdaa22168c235p-4L, strtold("inf", NULL)), CMPLXL(-0xc.90fdaa22168c234p-4L, strtold("inf", NULL)), 0);
	test(24, CMPLXL(0.0, strtold("inf", NULL)), CMPLXL(-0x0.000000000000001p-16385L, strtold("inf", NULL)), CMPLXL(0x0.0p+0L, strtold("inf", NULL)), CMPLXL(0x0.000000000000001p-16385L, strtold("inf", NULL)), 0);
	test(25, CMPLXL(0.9001, strtold("-inf", NULL)), CMPLXL(-0x0.000000000000001p-16385L, strtold("-inf", NULL)), CMPLXL(0x0.0p+0L, strtold("-inf", NULL)), CMPLXL(0x0.000000000000001p-16385L, strtold("-inf", NULL)), 0);
	test(26, CMPLXL(-0.1234, strtold("-inf", NULL)), CMPLXL(-0x0.000000000000001p-16385L, strtold("-inf", NULL)), CMPLXL(-0x0.0p+0L, strtold("-inf", NULL)), CMPLXL(0x0.000000000000001p-16385L, strtold("-inf", NULL)), 0);
	test(27, CMPLXL(nanl(""), strtold("-inf", NULL)), CMPLXL(nanl(""), strtold("-inf", NULL)), CMPLXL(nanl(""), strtold("-inf", NULL)), CMPLXL(nanl(""), strtold("-inf", NULL)), 0);
	test(28, CMPLXL(strtold("inf", NULL), strtold("-inf", NULL)), CMPLXL(0xc.90fdaa22168c234p-4L, strtold("-inf", NULL)), CMPLXL(0xc.90fdaa22168c235p-4L, strtold("-inf", NULL)), CMPLXL(0xc.90fdaa22168c236p-4L, strtold("-inf", NULL)), 0);
	test(29, CMPLXL(strtold("-inf", NULL), strtold("-inf", NULL)), CMPLXL(-0xc.90fdaa22168c236p-4L, strtold("-inf", NULL)), CMPLXL(-0xc.90fdaa22168c235p-4L, strtold("-inf", NULL)), CMPLXL(-0xc.90fdaa22168c234p-4L, strtold("-inf", NULL)), 0);
	test(30, CMPLXL(0.0, strtold("-inf", NULL)), CMPLXL(-0x0.000000000000001p-16385L, strtold("-inf", NULL)), CMPLXL(0x0.0p+0L, strtold("-inf", NULL)), CMPLXL(0x0.000000000000001p-16385L, strtold("-inf", NULL)), 0);
	test(31, CMPLXL(0.9001, 0.0), CMPLXL(0x8.f5c207244f40d7ap-3L, -0x0.000000000000001p-16385L), CMPLXL(0x8.f5c207244f40d7bp-3L, 0x0.0p+0L), CMPLXL(0x8.f5c207244f40d7cp-3L, 0x0.000000000000001p-16385L), 0);
	test(32, CMPLXL(-0.1234, 0.0), CMPLXL(-0xf.d5e78a341b64fbbp-7L, -0x0.000000000000001p-16385L), CMPLXL(-0xf.d5e78a341b64fbap-7L, 0x0.0p+0L), CMPLXL(-0xf.d5e78a341b64fb9p-7L, 0x0.000000000000001p-16385L), 0);
	test(33, CMPLXL(nanl(""), 0.0), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(34, CMPLXL(strtold("inf", NULL), 0.0), CMPLXL(0xc.90fdaa22168c234p-3L, strtold("inf", NULL)), CMPLXL(0xc.90fdaa22168c235p-3L, strtold("inf", NULL)), CMPLXL(0xc.90fdaa22168c236p-3L, strtold("inf", NULL)), 0);
	test(35, CMPLXL(strtold("-inf", NULL), 0.0), CMPLXL(-0xc.90fdaa22168c236p-3L, strtold("inf", NULL)), CMPLXL(-0xc.90fdaa22168c235p-3L, strtold("inf", NULL)), CMPLXL(-0xc.90fdaa22168c234p-3L, strtold("inf", NULL)), 0);
	test(36, CMPLXL(0.0, 0.0), CMPLXL(-0x0.000000000000001p-16385L, -0x0.000000000000001p-16385L), CMPLXL(0x0.0p+0L, 0x0.0p+0L), CMPLXL(0x0.000000000000001p-16385L, 0x0.000000000000001p-16385L), 0);
	return imprecise;
}
