/* Test whether a basic catanf invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <complex.h>
#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)
#define MF_ANYSIGN1 (1 << 2)
#define MF_ANYSIGN2 (1 << 3)

// Soft fail on rounding errors and report only one.
int imprecise;

void test(int variant, float complex input1, float complex lower, float complex expected, float complex upper, int flags)
{
	float complex output = catanf(input1);
	if ( !(flags & MF_UNSPEC1) )
	{
		float real = crealf(output);
		real = (flags & MF_ANYSIGN1) && real < 0.0 ? -real : real;
		float lower_real = crealf(lower);
		float expected_real = crealf(expected);
		float upper_real = crealf(upper);
		if ( !(isnan(expected_real) ? isnan(real) :
		       isfinite(expected_real) && expected_real != 0.0 ?
		       isfinite(real) && (real == expected_real || (lower_real < real && real < upper_real)) :
		       real == expected_real) )
		{
			if ( imprecise && isfinite(real) && isfinite(expected_real) )
				return;
			warnx("(%d.) catanf(%.4f + i*%.4f).real = %.6a, not %.6a, diff %.6a, ratio %.8g",
			     variant, crealf(input1), cimagf(input1), real, expected_real,
			     real - expected_real, real / expected_real);
			if ( !isfinite(real) || !isfinite(expected_real) )
				exit(1);
			imprecise = 1;
		}
		float imag = cimagf(output);
		imag = (flags & MF_ANYSIGN2) && imag < 0.0 ? -imag : imag;
		float lower_imag = cimagf(lower);
		float expected_imag = cimagf(expected);
		float upper_imag = cimagf(upper);
		if ( !(isnan(expected_imag) ? isnan(imag) :
		       isfinite(expected_imag) && expected_imag != 0.0 ?
		       isfinite(imag) && (imag == expected_imag || (lower_imag < imag && imag < upper_imag)) :
		       imag == expected_imag) )
		{
			if ( imprecise && isfinite(imag) && isfinite(expected_imag) )
				return;
			warnx("(%d.) catanf(%.4f + i*%.4f).imag = %.6a, not %.6a, diff %.6a, ratio %.8g",
			     variant, crealf(input1), cimagf(input1), imag, expected_imag,
			     imag - expected_imag, imag / expected_imag);
			if ( !isfinite(imag) || !isfinite(expected_imag) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, CMPLXF(90.01, 13.37), CMPLXF(0x1.8f5758p+0, 0x1.a736fap-10), CMPLXF(0x1.8f575ap+0, 0x1.a736fcp-10), CMPLXF(0x1.8f575cp+0, 0x1.a736fep-10), 0);
	test(2, CMPLXF(-12.34, 13.37), CMPLXF(-0x1.8891dcp+0, 0x1.4a9598p-5), CMPLXF(-0x1.8891dap+0, 0x1.4a959ap-5), CMPLXF(-0x1.8891d8p+0, 0x1.4a959cp-5), 0);
	test(3, CMPLXF(nanf(""), 13.37), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(4, CMPLXF(strtof("inf", NULL), 13.37), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, 0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(5, CMPLXF(strtof("-inf", NULL), 13.37), CMPLXF(-0x1.921fb8p+0, -0x1.0p-149), CMPLXF(-0x1.921fb6p+0, 0x0.0p+0), CMPLXF(-0x1.921fb4p+0, 0x1.0p-149), 0);
	test(6, CMPLXF(0.0, 13.37), CMPLXF(0x1.921fb4p+0, 0x1.32ee42p-4), CMPLXF(0x1.921fb6p+0, 0x1.32ee44p-4), CMPLXF(0x1.921fb8p+0, 0x1.32ee46p-4), 0);
	test(7, CMPLXF(90.01, -12.34), CMPLXF(0x1.8f551p+0, -0x1.87dd2ep-10), CMPLXF(0x1.8f5512p+0, -0x1.87dd2cp-10), CMPLXF(0x1.8f5514p+0, -0x1.87dd2ap-10), 0);
	test(8, CMPLXF(-12.34, -12.34), CMPLXF(-0x1.87bd62p+0, -0x1.4b909p-5), CMPLXF(-0x1.87bd6p+0, -0x1.4b908ep-5), CMPLXF(-0x1.87bd5ep+0, -0x1.4b908cp-5), 0);
	test(9, CMPLXF(nanf(""), -12.34), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(10, CMPLXF(strtof("inf", NULL), -12.34), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, -0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(11, CMPLXF(strtof("-inf", NULL), -12.34), CMPLXF(-0x1.921fb8p+0, -0x1.0p-149), CMPLXF(-0x1.921fb6p+0, -0x0.0p+0), CMPLXF(-0x1.921fb4p+0, 0x1.0p-149), 0);
	test(12, CMPLXF(0.0, -12.34), CMPLXF(0x1.921fb4p+0, -0x1.4ca87ep-4), CMPLXF(0x1.921fb6p+0, -0x1.4ca87cp-4), CMPLXF(0x1.921fb8p+0, -0x1.4ca87ap-4), 0);
	test(13, CMPLXF(90.01, nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(14, CMPLXF(-12.34, nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(15, CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(16, CMPLXF(strtof("inf", NULL), nanf("")), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, 0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0 | MF_ANYSIGN2);
	test(17, CMPLXF(strtof("-inf", NULL), nanf("")), CMPLXF(-0x1.921fb8p+0, -0x1.0p-149), CMPLXF(-0x1.921fb6p+0, 0x0.0p+0), CMPLXF(-0x1.921fb4p+0, 0x1.0p-149), 0 | MF_ANYSIGN2);
	test(18, CMPLXF(0.0, nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(19, CMPLXF(90.01, strtof("inf", NULL)), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, 0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(20, CMPLXF(-12.34, strtof("inf", NULL)), CMPLXF(-0x1.921fb8p+0, -0x1.0p-149), CMPLXF(-0x1.921fb6p+0, 0x0.0p+0), CMPLXF(-0x1.921fb4p+0, 0x1.0p-149), 0);
	test(21, CMPLXF(nanf(""), strtof("inf", NULL)), CMPLXF(nanf(""), -0x1.0p-149), CMPLXF(nanf(""), 0x0.0p+0), CMPLXF(nanf(""), 0x1.0p-149), 0);
	test(22, CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, 0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(23, CMPLXF(strtof("-inf", NULL), strtof("inf", NULL)), CMPLXF(-0x1.921fb8p+0, -0x1.0p-149), CMPLXF(-0x1.921fb6p+0, 0x0.0p+0), CMPLXF(-0x1.921fb4p+0, 0x1.0p-149), 0);
	test(24, CMPLXF(0.0, strtof("inf", NULL)), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, 0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(25, CMPLXF(90.01, strtof("-inf", NULL)), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, -0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(26, CMPLXF(-12.34, strtof("-inf", NULL)), CMPLXF(-0x1.921fb8p+0, -0x1.0p-149), CMPLXF(-0x1.921fb6p+0, -0x0.0p+0), CMPLXF(-0x1.921fb4p+0, 0x1.0p-149), 0);
	test(27, CMPLXF(nanf(""), strtof("-inf", NULL)), CMPLXF(nanf(""), -0x1.0p-149), CMPLXF(nanf(""), -0x0.0p+0), CMPLXF(nanf(""), 0x1.0p-149), 0);
	test(28, CMPLXF(strtof("inf", NULL), strtof("-inf", NULL)), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, -0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(29, CMPLXF(strtof("-inf", NULL), strtof("-inf", NULL)), CMPLXF(-0x1.921fb8p+0, -0x1.0p-149), CMPLXF(-0x1.921fb6p+0, -0x0.0p+0), CMPLXF(-0x1.921fb4p+0, 0x1.0p-149), 0);
	test(30, CMPLXF(0.0, strtof("-inf", NULL)), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, -0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(31, CMPLXF(90.01, 0.0), CMPLXF(0x1.8f47a2p+0, -0x1.0p-149), CMPLXF(0x1.8f47a4p+0, 0x0.0p+0), CMPLXF(0x1.8f47a6p+0, 0x1.0p-149), 0);
	test(32, CMPLXF(-12.34, 0.0), CMPLXF(-0x1.7d6c7p+0, -0x1.0p-149), CMPLXF(-0x1.7d6c6ep+0, 0x0.0p+0), CMPLXF(-0x1.7d6c6cp+0, 0x1.0p-149), 0);
	test(33, CMPLXF(nanf(""), 0.0), CMPLXF(nanf(""), -0x1.0p-149), CMPLXF(nanf(""), 0x0.0p+0), CMPLXF(nanf(""), 0x1.0p-149), 0);
	test(34, CMPLXF(strtof("inf", NULL), 0.0), CMPLXF(0x1.921fb4p+0, -0x1.0p-149), CMPLXF(0x1.921fb6p+0, 0x0.0p+0), CMPLXF(0x1.921fb8p+0, 0x1.0p-149), 0);
	test(35, CMPLXF(strtof("-inf", NULL), 0.0), CMPLXF(-0x1.921fb8p+0, -0x1.0p-149), CMPLXF(-0x1.921fb6p+0, 0x0.0p+0), CMPLXF(-0x1.921fb4p+0, 0x1.0p-149), 0);
	test(36, CMPLXF(0.0, 0.0), CMPLXF(-0x1.0p-149, -0x1.0p-149), CMPLXF(0x0.0p+0, 0x0.0p+0), CMPLXF(0x1.0p-149, 0x1.0p-149), 0);
	return imprecise;
}
