/* Test whether a basic cexpf invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <complex.h>
#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)
#define MF_ANYSIGN1 (1 << 2)
#define MF_ANYSIGN2 (1 << 3)

// Soft fail on rounding errors and report only one.
int imprecise;

void test(int variant, float complex input1, float complex lower, float complex expected, float complex upper, int flags)
{
	float complex output = cexpf(input1);
	if ( !(flags & MF_UNSPEC1) )
	{
		float real = crealf(output);
		real = (flags & MF_ANYSIGN1) && real < 0.0 ? -real : real;
		float lower_real = crealf(lower);
		float expected_real = crealf(expected);
		float upper_real = crealf(upper);
		if ( !(isnan(expected_real) ? isnan(real) :
		       isfinite(expected_real) && expected_real != 0.0 ?
		       isfinite(real) && (real == expected_real || (lower_real < real && real < upper_real)) :
		       real == expected_real) )
		{
			if ( imprecise && isfinite(real) && isfinite(expected_real) )
				return;
			warnx("(%d.) cexpf(%.4f + i*%.4f).real = %.6a, not %.6a, diff %.6a, ratio %.8g",
			     variant, crealf(input1), cimagf(input1), real, expected_real,
			     real - expected_real, real / expected_real);
			if ( !isfinite(real) || !isfinite(expected_real) )
				exit(1);
			imprecise = 1;
		}
		float imag = cimagf(output);
		imag = (flags & MF_ANYSIGN2) && imag < 0.0 ? -imag : imag;
		float lower_imag = cimagf(lower);
		float expected_imag = cimagf(expected);
		float upper_imag = cimagf(upper);
		if ( !(isnan(expected_imag) ? isnan(imag) :
		       isfinite(expected_imag) && expected_imag != 0.0 ?
		       isfinite(imag) && (imag == expected_imag || (lower_imag < imag && imag < upper_imag)) :
		       imag == expected_imag) )
		{
			if ( imprecise && isfinite(imag) && isfinite(expected_imag) )
				return;
			warnx("(%d.) cexpf(%.4f + i*%.4f).imag = %.6a, not %.6a, diff %.6a, ratio %.8g",
			     variant, crealf(input1), cimagf(input1), imag, expected_imag,
			     imag - expected_imag, imag / expected_imag);
			if ( !isfinite(imag) || !isfinite(expected_imag) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, CMPLXF(90.01, 13.37), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), 0);
	test(2, CMPLXF(-12.34, 13.37), CMPLXF(0x1.976a42p-19, 0x1.a68c42p-19), CMPLXF(0x1.976a44p-19, 0x1.a68c44p-19), CMPLXF(0x1.976a46p-19, 0x1.a68c46p-19), 0);
	test(3, CMPLXF(nanf(""), 13.37), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(4, CMPLXF(strtof("inf", NULL), 13.37), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), 0);
	test(5, CMPLXF(strtof("-inf", NULL), 13.37), CMPLXF(-0x1.0p-149, -0x1.0p-149), CMPLXF(0x0.0p+0, 0x0.0p+0), CMPLXF(0x1.0p-149, 0x1.0p-149), 0);
	test(6, CMPLXF(0.0, 13.37), CMPLXF(0x1.6360e4p-1, 0x1.709418p-1), CMPLXF(0x1.6360e6p-1, 0x1.70941ap-1), CMPLXF(0x1.6360e8p-1, 0x1.70941cp-1), 0);
	test(7, CMPLXF(90.01, -12.34), CMPLXF(strtof("inf", NULL), 0x1.a046cep+127), CMPLXF(strtof("inf", NULL), 0x1.a046dp+127), CMPLXF(strtof("inf", NULL), 0x1.a046d2p+127), 0);
	test(8, CMPLXF(-12.34, -12.34), CMPLXF(0x1.1dff56p-18, 0x1.077b44p-20), CMPLXF(0x1.1dff58p-18, 0x1.077b46p-20), CMPLXF(0x1.1dff5ap-18, 0x1.077b48p-20), 0);
	test(9, CMPLXF(nanf(""), -12.34), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(10, CMPLXF(strtof("inf", NULL), -12.34), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), 0);
	test(11, CMPLXF(strtof("-inf", NULL), -12.34), CMPLXF(-0x1.0p-149, -0x1.0p-149), CMPLXF(0x0.0p+0, 0x0.0p+0), CMPLXF(0x1.0p-149, 0x1.0p-149), 0);
	test(12, CMPLXF(0.0, -12.34), CMPLXF(0x1.f2f002p-1, 0x1.cba846p-3), CMPLXF(0x1.f2f004p-1, 0x1.cba848p-3), CMPLXF(0x1.f2f006p-1, 0x1.cba84ap-3), 0);
	test(13, CMPLXF(90.01, nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(14, CMPLXF(-12.34, nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(15, CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(16, CMPLXF(strtof("inf", NULL), nanf("")), CMPLXF(strtof("inf", NULL), nanf("")), CMPLXF(strtof("inf", NULL), nanf("")), CMPLXF(strtof("inf", NULL), nanf("")), 0);
	test(17, CMPLXF(strtof("-inf", NULL), nanf("")), CMPLXF(-0x1.0p-149, -0x1.0p-149), CMPLXF(0x0.0p+0, 0x0.0p+0), CMPLXF(0x1.0p-149, 0x1.0p-149), 0);
	test(18, CMPLXF(0.0, nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(19, CMPLXF(90.01, strtof("inf", NULL)), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(20, CMPLXF(-12.34, strtof("inf", NULL)), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(21, CMPLXF(nanf(""), strtof("inf", NULL)), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(22, CMPLXF(strtof("inf", NULL), strtof("inf", NULL)), CMPLXF(strtof("inf", NULL), nanf("")), CMPLXF(strtof("inf", NULL), nanf("")), CMPLXF(strtof("inf", NULL), nanf("")), 0);
	test(23, CMPLXF(strtof("-inf", NULL), strtof("inf", NULL)), CMPLXF(-0x1.0p-149, -0x1.0p-149), CMPLXF(0x0.0p+0, 0x0.0p+0), CMPLXF(0x1.0p-149, 0x1.0p-149), 0);
	test(24, CMPLXF(0.0, strtof("inf", NULL)), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(25, CMPLXF(90.01, strtof("-inf", NULL)), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(26, CMPLXF(-12.34, strtof("-inf", NULL)), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(27, CMPLXF(nanf(""), strtof("-inf", NULL)), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(28, CMPLXF(strtof("inf", NULL), strtof("-inf", NULL)), CMPLXF(strtof("inf", NULL), nanf("")), CMPLXF(strtof("inf", NULL), nanf("")), CMPLXF(strtof("inf", NULL), nanf("")), 0);
	test(29, CMPLXF(strtof("-inf", NULL), strtof("-inf", NULL)), CMPLXF(-0x1.0p-149, -0x1.0p-149), CMPLXF(0x0.0p+0, -0x0.0p+0), CMPLXF(0x1.0p-149, 0x1.0p-149), 0);
	test(30, CMPLXF(0.0, strtof("-inf", NULL)), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), CMPLXF(nanf(""), nanf("")), 0);
	test(31, CMPLXF(90.01, 0.0), CMPLXF(strtof("inf", NULL), -0x1.0p-149), CMPLXF(strtof("inf", NULL), 0x0.0p+0), CMPLXF(strtof("inf", NULL), 0x1.0p-149), 0);
	test(32, CMPLXF(-12.34, 0.0), CMPLXF(0x1.257c28p-18, -0x1.0p-149), CMPLXF(0x1.257c2ap-18, 0x0.0p+0), CMPLXF(0x1.257c2cp-18, 0x1.0p-149), 0);
	test(33, CMPLXF(nanf(""), 0.0), CMPLXF(nanf(""), -0x1.0p-149), CMPLXF(nanf(""), 0x0.0p+0), CMPLXF(nanf(""), 0x1.0p-149), 0);
	test(34, CMPLXF(strtof("inf", NULL), 0.0), CMPLXF(strtof("inf", NULL), -0x1.0p-149), CMPLXF(strtof("inf", NULL), 0x0.0p+0), CMPLXF(strtof("inf", NULL), 0x1.0p-149), 0);
	test(35, CMPLXF(strtof("-inf", NULL), 0.0), CMPLXF(-0x1.0p-149, -0x1.0p-149), CMPLXF(0x0.0p+0, 0x0.0p+0), CMPLXF(0x1.0p-149, 0x1.0p-149), 0);
	test(36, CMPLXF(0.0, 0.0), CMPLXF(0x1.fffffep-1, -0x1.0p-149), CMPLXF(0x1.0p+0, 0x0.0p+0), CMPLXF(0x1.000002p+0, 0x1.0p-149), 0);
	return imprecise;
}
