/* Test whether a basic clogl invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <complex.h>
#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)
#define MF_ANYSIGN1 (1 << 2)
#define MF_ANYSIGN2 (1 << 3)

// Soft fail on rounding errors and report only one.
int imprecise;

void test(int variant, long double complex input1, long double complex lower, long double complex expected, long double complex upper, int flags)
{
	long double complex output = clogl(input1);
	if ( !(flags & MF_UNSPEC1) )
	{
		long double real = creall(output);
		real = (flags & MF_ANYSIGN1) && real < 0.0 ? -real : real;
		long double lower_real = creall(lower);
		long double expected_real = creall(expected);
		long double upper_real = creall(upper);
		if ( !(isnan(expected_real) ? isnan(real) :
		       isfinite(expected_real) && expected_real != 0.0 ?
		       isfinite(real) && (real == expected_real || (lower_real < real && real < upper_real)) :
		       real == expected_real) )
		{
			if ( imprecise && isfinite(real) && isfinite(expected_real) )
				return;
			warnx("(%d.) clogl(%.4Lf + i*%.4Lf).real = %.17La, not %.17La, diff %.17La, ratio %.20Lg",
			     variant, creall(input1), cimagl(input1), real, expected_real,
			     real - expected_real, real / expected_real);
			if ( !isfinite(real) || !isfinite(expected_real) )
				exit(1);
			imprecise = 1;
		}
		long double imag = cimagl(output);
		imag = (flags & MF_ANYSIGN2) && imag < 0.0 ? -imag : imag;
		long double lower_imag = cimagl(lower);
		long double expected_imag = cimagl(expected);
		long double upper_imag = cimagl(upper);
		if ( !(isnan(expected_imag) ? isnan(imag) :
		       isfinite(expected_imag) && expected_imag != 0.0 ?
		       isfinite(imag) && (imag == expected_imag || (lower_imag < imag && imag < upper_imag)) :
		       imag == expected_imag) )
		{
			if ( imprecise && isfinite(imag) && isfinite(expected_imag) )
				return;
			warnx("(%d.) clogl(%.4Lf + i*%.4Lf).imag = %.17La, not %.17La, diff %.17La, ratio %.20Lg",
			     variant, creall(input1), cimagl(input1), imag, expected_imag,
			     imag - expected_imag, imag / expected_imag);
			if ( !isfinite(imag) || !isfinite(expected_imag) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, CMPLXL(90.01, 13.37), CMPLXL(0x9.058bdf0928e62b9p-1L, 0x9.6fff98f3e8e5142p-6L), CMPLXL(0x9.058bdf0928e62bap-1L, 0x9.6fff98f3e8e5143p-6L), CMPLXL(0x9.058bdf0928e62bbp-1L, 0x9.6fff98f3e8e5144p-6L), 0);
	test(2, CMPLXL(-12.34, 13.37), CMPLXL(0xb.9abc20f0b5029b6p-2L, 0x9.43bdc9a55e5ecdp-2L), CMPLXL(0xb.9abc20f0b5029b7p-2L, 0x9.43bdc9a55e5ecd1p-2L), CMPLXL(0xb.9abc20f0b5029b8p-2L, 0x9.43bdc9a55e5ecd2p-2L), 0);
	test(3, CMPLXL(nanl(""), 13.37), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(4, CMPLXL(strtold("inf", NULL), 13.37), CMPLXL(strtold("inf", NULL), -0x0.000000000000001p-16385L), CMPLXL(strtold("inf", NULL), 0x0.0p+0L), CMPLXL(strtold("inf", NULL), 0x0.000000000000001p-16385L), 0);
	test(5, CMPLXL(strtold("-inf", NULL), 13.37), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c234p-2L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c235p-2L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c236p-2L), 0);
	test(6, CMPLXL(0.0, 13.37), CMPLXL(0xa.5f3ee703b23a3cep-2L, 0xc.90fdaa22168c234p-3L), CMPLXL(0xa.5f3ee703b23a3cfp-2L, 0xc.90fdaa22168c235p-3L), CMPLXL(0xa.5f3ee703b23a3dp-2L, 0xc.90fdaa22168c236p-3L), 0);
	test(7, CMPLXL(90.01, -12.34), CMPLXL(0x9.04b9f35d1921e73p-1L, -0x8.b843508193366c3p-6L), CMPLXL(0x9.04b9f35d1921e74p-1L, -0x8.b843508193366c2p-6L), CMPLXL(0x9.04b9f35d1921e75p-1L, -0x8.b843508193366c1p-6L), 0);
	test(8, CMPLXL(-12.34, -12.34), CMPLXL(0xb.700bb1a49d080e7p-2L, -0x9.6cbe3f9990e91a9p-2L), CMPLXL(0xb.700bb1a49d080e8p-2L, -0x9.6cbe3f9990e91a8p-2L), CMPLXL(0xb.700bb1a49d080e9p-2L, -0x9.6cbe3f9990e91a7p-2L), 0);
	test(9, CMPLXL(nanl(""), -12.34), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(10, CMPLXL(strtold("inf", NULL), -12.34), CMPLXL(strtold("inf", NULL), -0x0.000000000000001p-16385L), CMPLXL(strtold("inf", NULL), -0x0.0p+0L), CMPLXL(strtold("inf", NULL), 0x0.000000000000001p-16385L), 0);
	test(11, CMPLXL(strtold("-inf", NULL), -12.34), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c236p-2L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c235p-2L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c234p-2L), 0);
	test(12, CMPLXL(0.0, -12.34), CMPLXL(0xa.0d2781b4f9691b1p-2L, -0xc.90fdaa22168c236p-3L), CMPLXL(0xa.0d2781b4f9691b2p-2L, -0xc.90fdaa22168c235p-3L), CMPLXL(0xa.0d2781b4f9691b3p-2L, -0xc.90fdaa22168c234p-3L), 0);
	test(13, CMPLXL(90.01, nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(14, CMPLXL(-12.34, nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(15, CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(16, CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), 0);
	test(17, CMPLXL(strtold("-inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), 0);
	test(18, CMPLXL(0.0, nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(19, CMPLXL(90.01, strtold("inf", NULL)), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c234p-3L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c235p-3L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c236p-3L), 0);
	test(20, CMPLXL(-12.34, strtold("inf", NULL)), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c234p-3L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c235p-3L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c236p-3L), 0);
	test(21, CMPLXL(nanl(""), strtold("inf", NULL)), CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), 0);
	test(22, CMPLXL(strtold("inf", NULL), strtold("inf", NULL)), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c234p-4L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c235p-4L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c236p-4L), 0);
	test(23, CMPLXL(strtold("-inf", NULL), strtold("inf", NULL)), CMPLXL(strtold("inf", NULL), 0x9.6cbe3f9990e91a7p-2L), CMPLXL(strtold("inf", NULL), 0x9.6cbe3f9990e91a8p-2L), CMPLXL(strtold("inf", NULL), 0x9.6cbe3f9990e91a9p-2L), 0);
	test(24, CMPLXL(0.0, strtold("inf", NULL)), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c234p-3L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c235p-3L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c236p-3L), 0);
	test(25, CMPLXL(90.01, strtold("-inf", NULL)), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c236p-3L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c235p-3L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c234p-3L), 0);
	test(26, CMPLXL(-12.34, strtold("-inf", NULL)), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c236p-3L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c235p-3L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c234p-3L), 0);
	test(27, CMPLXL(nanl(""), strtold("-inf", NULL)), CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), CMPLXL(strtold("inf", NULL), nanl("")), 0);
	test(28, CMPLXL(strtold("inf", NULL), strtold("-inf", NULL)), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c236p-4L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c235p-4L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c234p-4L), 0);
	test(29, CMPLXL(strtold("-inf", NULL), strtold("-inf", NULL)), CMPLXL(strtold("inf", NULL), -0x9.6cbe3f9990e91a9p-2L), CMPLXL(strtold("inf", NULL), -0x9.6cbe3f9990e91a8p-2L), CMPLXL(strtold("inf", NULL), -0x9.6cbe3f9990e91a7p-2L), 0);
	test(30, CMPLXL(0.0, strtold("-inf", NULL)), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c236p-3L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c235p-3L), CMPLXL(strtold("inf", NULL), -0xc.90fdaa22168c234p-3L), 0);
	test(31, CMPLXL(90.01, 0.0), CMPLXL(0x8.fff59da8be1a523p-1L, -0x0.000000000000001p-16385L), CMPLXL(0x8.fff59da8be1a524p-1L, 0x0.0p+0L), CMPLXL(0x8.fff59da8be1a525p-1L, 0x0.000000000000001p-16385L), 0);
	test(32, CMPLXL(-12.34, 0.0), CMPLXL(0xa.0d2781b4f9691b1p-2L, 0xc.90fdaa22168c234p-2L), CMPLXL(0xa.0d2781b4f9691b2p-2L, 0xc.90fdaa22168c235p-2L), CMPLXL(0xa.0d2781b4f9691b3p-2L, 0xc.90fdaa22168c236p-2L), 0);
	test(33, CMPLXL(nanl(""), 0.0), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), CMPLXL(nanl(""), nanl("")), 0);
	test(34, CMPLXL(strtold("inf", NULL), 0.0), CMPLXL(strtold("inf", NULL), -0x0.000000000000001p-16385L), CMPLXL(strtold("inf", NULL), 0x0.0p+0L), CMPLXL(strtold("inf", NULL), 0x0.000000000000001p-16385L), 0);
	test(35, CMPLXL(strtold("-inf", NULL), 0.0), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c234p-2L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c235p-2L), CMPLXL(strtold("inf", NULL), 0xc.90fdaa22168c236p-2L), 0);
	test(36, CMPLXL(0.0, 0.0), CMPLXL(strtold("-inf", NULL), -0x0.000000000000001p-16385L), CMPLXL(strtold("-inf", NULL), 0x0.0p+0L), CMPLXL(strtold("-inf", NULL), 0x0.000000000000001p-16385L), 0);
	return imprecise;
}
