import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const playgroundDir = resolve(fileURLToPath(new URL("..", import.meta.url)));
const workerSourcePath = resolve(playgroundDir, "../browser/src/worker.ts");
const workerSourceDir = dirname(workerSourcePath);
const workerOutputPath = resolve(playgroundDir, "agentos-worker.js");
const appSourcePath = resolve(playgroundDir, "frontend/app.ts");
const appOutputPath = resolve(playgroundDir, "dist/app.js");
const runtimeHarnessSourcePath = resolve(
	playgroundDir,
	"frontend/runtime-harness.ts",
);
const runtimeHarnessOutputPath = resolve(
	playgroundDir,
	"dist/runtime-harness.js",
);
const betterSqliteShimPath = resolve(
	playgroundDir,
	"frontend/shims/better-sqlite3.ts",
);
const nodeFsPromisesShimPath = resolve(
	playgroundDir,
	"frontend/shims/node-fs-promises.ts",
);
const nodeFsShimPath = resolve(playgroundDir, "frontend/shims/node-fs.ts");
const nodeModuleShimPath = resolve(
	playgroundDir,
	"frontend/shims/node-module.ts",
);
const nodePathShimPath = resolve(playgroundDir, "frontend/shims/node-path.ts");
const nodeUtilShimPath = resolve(playgroundDir, "frontend/shims/node-util.ts");

const nodeBuiltinAlias = {
	"better-sqlite3": betterSqliteShimPath,
	fs: nodeFsShimPath,
	"fs/promises": nodeFsPromisesShimPath,
	module: nodeModuleShimPath,
	path: nodePathShimPath,
	"node:fs/promises": nodeFsPromisesShimPath,
	"node:module": nodeModuleShimPath,
	"node:path": nodePathShimPath,
	util: nodeUtilShimPath,
} as const;

const playgroundAlias = {
	"@rivet-dev/agentos-browser": resolve(
		playgroundDir,
		"../browser/src/index.ts",
	),
	...nodeBuiltinAlias,
} as const;

const BRIDGE_IMPORT_BLOCK = `\tlet bridgeModule: Record<string, unknown>;
\ttry {
\t\tbridgeModule = await dynamicImportModule("../bridge/index.js");
\t} catch {
\t\t// Vite browser tests execute source files directly, so \`.ts\` fallback is required.
\t\tbridgeModule = await dynamicImportModule("../bridge/index.ts");
\t}`;

async function writeGeneratedBundle(
	outputPath: string,
	sourcePath: string,
): Promise<void> {
	const outputSource = await readFile(outputPath, "utf8");
	await writeFile(outputPath, `// Generated by ${sourcePath}\n${outputSource}`);
}

async function buildWorkerBundle(): Promise<void> {
	const originalSource = await readFile(workerSourcePath, "utf8");
	const patchedSource = originalSource
		.replace(
			'import { mkdir } from "../fs-helpers.js";',
			'import { mkdir } from "../fs-helpers.js";\nimport * as browserWorkerBridgeModule from "../bridge/index.ts";',
		)
		.replace(
			BRIDGE_IMPORT_BLOCK,
			"\tconst bridgeModule = browserWorkerBridgeModule;",
		);

	await build({
		bundle: true,
		alias: nodeBuiltinAlias,
		format: "esm",
		legalComments: "none",
		minify: true,
		outfile: workerOutputPath,
		platform: "browser",
		stdin: {
			contents: patchedSource,
			loader: "ts",
			resolveDir: workerSourceDir,
			sourcefile: workerSourcePath,
		},
		target: "es2022",
	});

	await writeGeneratedBundle(
		workerOutputPath,
		"packages/playground/scripts/build-worker.ts",
	);
}

async function buildAppBundle(): Promise<void> {
	await build({
		bundle: true,
		alias: playgroundAlias,
		entryPoints: [appSourcePath],
		format: "esm",
		legalComments: "none",
		outfile: appOutputPath,
		platform: "browser",
		target: "es2022",
	});

	await writeGeneratedBundle(
		appOutputPath,
		"packages/playground/scripts/build-worker.ts",
	);
}

async function buildRuntimeHarnessBundle(): Promise<void> {
	await build({
		bundle: true,
		alias: playgroundAlias,
		entryPoints: [runtimeHarnessSourcePath],
		format: "esm",
		legalComments: "none",
		outfile: runtimeHarnessOutputPath,
		platform: "browser",
		target: "es2022",
	});

	await writeGeneratedBundle(
		runtimeHarnessOutputPath,
		"packages/playground/scripts/build-worker.ts",
	);
}

async function main(): Promise<void> {
	await Promise.all([
		buildWorkerBundle(),
		buildAppBundle(),
		buildRuntimeHarnessBundle(),
	]);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
