import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const require = createRequire(import.meta.url);
const playgroundDir = resolve(fileURLToPath(new URL("..", import.meta.url)));
// Converged: the worker is @rivet-dev/agentos-runtime-browser's, bundled as-is (no source
// patching — the converged driver wires the bridge via the convergedSidecar
// option, not by injecting it into the worker source). Resolve it through the
// @rivet-dev/agentos-browser package (which depends on the runtime browser);
// the playground itself does not depend on the runtime browser directly.
const requireFromBrowserPkg = createRequire(
	require.resolve("@rivet-dev/agentos-browser"),
);
const workerSourcePath = requireFromBrowserPkg.resolve(
	"@rivet-dev/agentos-runtime-browser/internal/worker",
);
const workerOutputPath = resolve(playgroundDir, "agentos-worker.js");
const appSourcePath = resolve(playgroundDir, "frontend/app.ts");
const appOutputPath = resolve(playgroundDir, "dist/app.js");
const runtimeHarnessSourcePath = resolve(
	playgroundDir,
	"frontend/runtime-harness.ts",
);
const runtimeHarnessOutputPath = resolve(
	playgroundDir,
	"dist/runtime-harness.js",
);
const betterSqliteShimPath = resolve(
	playgroundDir,
	"frontend/shims/better-sqlite3.ts",
);
const nodeFsPromisesShimPath = resolve(
	playgroundDir,
	"frontend/shims/node-fs-promises.ts",
);
const nodeFsShimPath = resolve(playgroundDir, "frontend/shims/node-fs.ts");
const nodeModuleShimPath = resolve(
	playgroundDir,
	"frontend/shims/node-module.ts",
);
const nodePathShimPath = resolve(playgroundDir, "frontend/shims/node-path.ts");
const nodeUtilShimPath = resolve(playgroundDir, "frontend/shims/node-util.ts");

const nodeBuiltinAlias = {
	"better-sqlite3": betterSqliteShimPath,
	fs: nodeFsShimPath,
	"fs/promises": nodeFsPromisesShimPath,
	module: nodeModuleShimPath,
	path: nodePathShimPath,
	"node:fs/promises": nodeFsPromisesShimPath,
	"node:module": nodeModuleShimPath,
	"node:path": nodePathShimPath,
	util: nodeUtilShimPath,
} as const;

const playgroundAlias = {
	"@rivet-dev/agentos-browser": resolve(
		playgroundDir,
		"../browser/src/index.ts",
	),
	...nodeBuiltinAlias,
} as const;

async function writeGeneratedBundle(
	outputPath: string,
	sourcePath: string,
): Promise<void> {
	const outputSource = await readFile(outputPath, "utf8");
	await writeFile(outputPath, `// Generated by ${sourcePath}\n${outputSource}`);
}

async function buildWorkerBundle(): Promise<void> {
	await build({
		bundle: true,
		alias: nodeBuiltinAlias,
		entryPoints: [workerSourcePath],
		format: "esm",
		legalComments: "none",
		minify: true,
		outfile: workerOutputPath,
		platform: "browser",
		target: "es2022",
	});

	await writeGeneratedBundle(
		workerOutputPath,
		"packages/playground/scripts/build-worker.ts",
	);
}

async function buildAppBundle(): Promise<void> {
	await build({
		bundle: true,
		alias: playgroundAlias,
		entryPoints: [appSourcePath],
		format: "esm",
		legalComments: "none",
		outfile: appOutputPath,
		platform: "browser",
		target: "es2022",
	});

	await writeGeneratedBundle(
		appOutputPath,
		"packages/playground/scripts/build-worker.ts",
	);
}

async function buildRuntimeHarnessBundle(): Promise<void> {
	await build({
		bundle: true,
		alias: playgroundAlias,
		entryPoints: [runtimeHarnessSourcePath],
		format: "esm",
		legalComments: "none",
		outfile: runtimeHarnessOutputPath,
		platform: "browser",
		target: "es2022",
	});

	await writeGeneratedBundle(
		runtimeHarnessOutputPath,
		"packages/playground/scripts/build-worker.ts",
	);
}

async function main(): Promise<void> {
	await Promise.all([
		buildWorkerBundle(),
		buildAppBundle(),
		buildRuntimeHarnessBundle(),
	]);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
