//! Native compatibility exports for shared VM-scoped runtime limits.

pub use crate::core::limits::{
    validate_vm_limits, HostFunctionLimits, HttpLimits, JsRuntimeLimits, PluginLimits,
    ProcessLimits, PythonLimits, SqliteLimits, VmLimits, WasmLimits,
    DEFAULT_HOST_FUNCTION_TIMEOUT_MS, DEFAULT_JS_CAPTURED_OUTPUT_LIMIT_BYTES,
    DEFAULT_JS_EVENT_PAYLOAD_LIMIT_BYTES, DEFAULT_JS_STDIN_BUFFER_LIMIT_BYTES,
    DEFAULT_MAX_FETCH_RESPONSE_BYTES, DEFAULT_PROCESS_MAX_PENDING_CHILD_SYNC_BYTES,
    DEFAULT_PROCESS_MAX_PENDING_CHILD_SYNC_COUNT, DEFAULT_PROCESS_PENDING_EVENT_BYTES,
    DEFAULT_PROCESS_PENDING_EVENT_COUNT, DEFAULT_PROCESS_PENDING_STDIN_BYTES,
    DEFAULT_PYTHON_EXECUTION_TIMEOUT_MS, DEFAULT_PYTHON_MAX_OLD_SPACE_MB,
    DEFAULT_PYTHON_OUTPUT_BUFFER_MAX_BYTES, DEFAULT_PYTHON_VFS_RPC_TIMEOUT_MS,
    DEFAULT_SQLITE_MAX_RESULT_BYTES, DEFAULT_V8_HEAP_LIMIT_MB, DEFAULT_V8_IPC_MAX_FRAME_BYTES,
    DEFAULT_WASM_CAPTURED_OUTPUT_LIMIT_BYTES, DEFAULT_WASM_MAX_MODULE_FILE_BYTES,
    DEFAULT_WASM_SYNC_READ_LIMIT_BYTES, MAX_EXAMPLES_PER_HOST_FUNCTION,
    MAX_HOST_FUNCTIONS_PER_COLLECTION, MAX_HOST_FUNCTION_EXAMPLE_INPUT_BYTES,
    MAX_HOST_FUNCTION_SCHEMA_BYTES, MAX_HOST_FUNCTION_TIMEOUT_MS, MAX_PERSISTED_MANIFEST_BYTES,
    MAX_PERSISTED_MANIFEST_FILE_BYTES, MAX_REGISTERED_HOST_FUNCTIONS_PER_VM,
    MAX_REGISTERED_HOST_FUNCTION_COLLECTIONS,
};

pub const DEFAULT_EXTENSION_OUTPUT_BUFFER_BYTE_LIMIT: usize = 1024 * 1024;
use agentos_vm_config::VmLimitsConfig;

use crate::state::VmError;

pub fn vm_limits_from_config(
    config: Option<&VmLimitsConfig>,
    sidecar_max_frame_bytes: usize,
) -> Result<VmLimits, VmError> {
    crate::core::limits::vm_limits_from_config(config, sidecar_max_frame_bytes)
        .map_err(|error| VmError::InvalidState(error.to_string()))
}
