import { existsSync, readFileSync, statSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig, type Plugin } from "vite";

// The symlinked @rivet-dev/agentos-runtime-browser + /core dist files (served via /@fs from a
// sibling checkout) import bare deps that live in THIS package's store, not the
// sibling's. Vite resolves bare imports relative to the importing file, so those
// fail. Alias each to its agent-os-web-resolved location (resolved at config time
// so it survives version bumps). Add new names here if a dist import 500s.
const requireHere = createRequire(import.meta.url);
const ALIASED_DIST_DEPS = ["@rivetkit/bare-ts", "sucrase"];
function distDepAliases(): Record<string, string> {
	const aliases: Record<string, string> = {};
	for (const name of ALIASED_DIST_DEPS) {
		try {
			aliases[name] = path.dirname(requireHere.resolve(`${name}/package.json`));
		} catch {
			// not installed / not needed; skip
		}
	}
	return aliases;
}

// Dev server for the in-browser pi TUI / real-terminal manual-test pages.
// Replaces the hand-rolled tests/browser-wasm/serve.mjs with Vite (TS + HMR on
// the entry source) while keeping the three things the page actually needs:
//   1. COOP/COEP so SharedArrayBuffer (the converged sync-bridge) is available.
//   2. /wasm/* served from the built agentos-sidecar wasm-web cache.
//   3. a mock Anthropic /v1/messages endpoint for the older pi-prompt/demo paths.
// The prebuilt static assets the entry fetch()es at runtime (pi-cli.bundle.cjs,
// pi-package.json, pi-theme-*.json, agentos-worker.js) live in the root dir and
// are served statically by Vite as-is.

const here = path.dirname(fileURLToPath(import.meta.url));
const browserWasmDir = path.join(here, "tests", "browser-wasm");
const wasmDir = path.join(here, ".cache", "agentos-sidecar-wasm-web");
const commandsDir = path.join(browserWasmDir, "commands");
const repoRoot = path.resolve(here, "..", "..");
// @rivet-dev/agentos-runtime-browser is symlinked to a sibling checkout; allow Vite to read it.
const secureExecCheckout = path.resolve(repoRoot, "..", "secure-exec-convwasi");
// The entry imports `buffer` for the Buffer polyfill; Vite would otherwise
// externalize the Node builtin. Point it at the npm `buffer` package (same as the
// esbuild gate build's `--alias:buffer=...`).
const bufferPolyfill = path.join(
	repoRoot,
	"node_modules",
	".pnpm",
	"buffer@6.0.3",
	"node_modules",
	"buffer",
);

const PI_SENTINEL = "PONG_FROM_PI_IN_BROWSER";

function mockReplyFor(requestBody: string): string {
	let text = "";
	try {
		const parsed = JSON.parse(requestBody);
		const messages = Array.isArray(parsed.messages) ? parsed.messages : [];
		for (let i = messages.length - 1; i >= 0; i -= 1) {
			if (messages[i].role !== "user") continue;
			const content = messages[i].content;
			text =
				typeof content === "string"
					? content
					: Array.isArray(content)
						? content.map((p: { text?: string }) => p?.text || "").join("")
						: "";
			break;
		}
	} catch {}
	const q = text.toLowerCase();
	if (/\bpong\b/.test(q)) return PI_SENTINEL;
	if (/2\s*\+\s*2|two plus two/.test(q)) return "2 + 2 = 4.";
	if (/capital of france/.test(q)) return "The capital of France is Paris.";
	const clean = text.trim().slice(0, 200);
	return clean
		? `You asked: "${clean}". This reply was generated by pi running in the browser.`
		: PI_SENTINEL;
}

function anthropicSse(text: string): string {
	const ev = (event: string, data: unknown) =>
		`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
	return (
		ev("message_start", { type: "message_start", message: { id: "msg_mock", type: "message", role: "assistant", model: "claude-mock", content: [], stop_reason: null, stop_sequence: null, usage: { input_tokens: 1, output_tokens: 1 } } }) +
		ev("content_block_start", { type: "content_block_start", index: 0, content_block: { type: "text", text: "" } }) +
		ev("content_block_delta", { type: "content_block_delta", index: 0, delta: { type: "text_delta", text } }) +
		ev("content_block_stop", { type: "content_block_stop", index: 0 }) +
		ev("message_delta", { type: "message_delta", delta: { stop_reason: "end_turn", stop_sequence: null }, usage: { output_tokens: 1 } }) +
		ev("message_stop", { type: "message_stop" })
	);
}

function sendBinary(res: import("node:http").ServerResponse, file: string, contentType: string): void {
	const body = readFileSync(file);
	res.setHeader("Content-Type", contentType);
	res.setHeader("Content-Length", String(body.byteLength));
	res.setHeader("Cache-Control", "no-store");
	res.end(body);
}

// The converged guest `fetch` (the wasi-command-host loads command wasm this way)
// round-trips the response body through UTF-8 text, which mangles raw binary and
// inflates its length (lone bytes -> U+FFFD), corrupting the wasm. The runtime
// already supports an `x-body-encoding: base64` opt-out that the guest atob-decodes
// (see readCommandBytes / wasi-command-bootstrap), so serve command wasm base64 to
// survive that text hop intact.
function sendBase64Binary(res: import("node:http").ServerResponse, file: string): void {
	const b64 = readFileSync(file).toString("base64");
	res.setHeader("Content-Type", "text/plain; charset=utf-8");
	res.setHeader("x-body-encoding", "base64");
	res.setHeader("Content-Length", String(Buffer.byteLength(b64)));
	res.setHeader("Cache-Control", "no-store");
	res.end(b64);
}

function agentosDevServer(): Plugin {
	return {
		name: "agentos-dev-server",
		configureServer(server) {
			server.middlewares.use((req, res, next) => {
				const urlPath = decodeURIComponent((req.url ?? "/").split("?")[0]);


				// Mock Anthropic endpoint (older pi-prompt/demo paths).
				if (urlPath === "/v1/messages") {
					const cors = {
						"Access-Control-Allow-Origin": "*",
						"Access-Control-Allow-Methods": "POST, OPTIONS",
						"Access-Control-Allow-Headers": "*",
						"Cross-Origin-Resource-Policy": "cross-origin",
						"Cross-Origin-Embedder-Policy": "require-corp",
					};
					if (req.method === "OPTIONS") {
						res.writeHead(204, cors).end();
						return;
					}
					let body = "";
					req.on("data", (c) => (body += c));
					req.on("end", () => {
						res
							.writeHead(200, { ...cors, "Content-Type": "text/event-stream" })
							.end(anthropicSse(mockReplyFor(body)));
					});
					return;
				}

				// Built agentos wasm-web package at /wasm/*.
				if (urlPath.startsWith("/wasm/")) {
					const file = path.join(wasmDir, urlPath.slice("/wasm/".length));
					if (file.startsWith(wasmDir) && existsSync(file) && statSync(file).isFile()) {
						sendBinary(
							res,
							file,
							file.endsWith(".wasm") ? "application/wasm" : "text/javascript; charset=utf-8",
						);
						return;
					}
					res.writeHead(404).end(`not found: ${urlPath}`);
					return;
				}

				// Real wasm command binaries at /commands/* (extensionless). Serve raw
				// AND fully buffered with an explicit Content-Length: the guest fetch is
				// reassembled over the converged sync-bridge SAB, and a chunked response
				// with no length corrupts at the buffer boundary.
				if (urlPath.startsWith("/commands/")) {
					const file = path.join(commandsDir, urlPath.slice("/commands/".length));
					if (file.startsWith(commandsDir) && existsSync(file) && statSync(file).isFile()) {
						sendBase64Binary(res, file);
						return;
					}
					res.writeHead(404).end(`not found: ${urlPath}`);
					return;
				}

				next();
			});
		},
	};
}

export default defineConfig({
	root: browserWasmDir,
	server: {
		port: 5173,
		strictPort: false,
		headers: {
			"Cross-Origin-Opener-Policy": "same-origin",
			"Cross-Origin-Embedder-Policy": "require-corp",
		},
		fs: {
			allow: [browserWasmDir, here, wasmDir, repoRoot, secureExecCheckout],
		},
	},
	resolve: {
		alias: { buffer: bufferPolyfill, ...distDepAliases() },
	},
	optimizeDeps: {
		// The symlinked dist dep + the runtime-fetched .cjs bundles should not be
		// pre-bundled; the entry imports them lazily / at runtime.
		exclude: ["@rivet-dev/agentos-runtime-browser"],
		include: ["buffer"],
	},
	plugins: [agentosDevServer()],
	// The `root: browserWasmDir` above is for the dev server (serving the
	// in-browser test pages). Vitest must NOT inherit it, or `vitest run
	// tests/runtime-driver` resolves against tests/browser-wasm and finds no
	// files. Pin the test root to the package root and scope discovery to the
	// vitest suites (the playwright *.spec.ts under tests/browser-wasm are run
	// separately by `test:browser-wasm`, not vitest).
	test: {
		root: here,
		include: ["tests/runtime-driver/**/*.test.ts"],
	},
});
