export type {
	AgentExitEvent,
	AgentExitHandler,
	AgentOsCreateSidecarOptions,
	AgentOsLimits,
	AgentOsOptions,
	AgentOsSharedSidecarOptions,
	AgentOsSidecarConfig,
	AgentOsSidecarDescription,
	AgentOsSidecarRuntimeConfig,
	AgentRegistryEntry,
	AgentRestartOutcome,
	AgentStderrEvent,
	AgentStderrHandler,
	BatchReadResult,
	BatchWriteEntry,
	BatchWriteResult,
	DirEntry,
	DynamicMountDescriptor,
	ExportRootFilesystemOptions,
	HttpRequest,
	HttpResponse,
	LimitWarning,
	LimitWarningHandler,
	MountConfig,
	MountConfigJsonObject,
	MountConfigJsonPrimitive,
	MountConfigJsonValue,
	MountInfo,
	NativeMountConfig,
	NativeMountPluginDescriptor,
	NativeRootFilesystemConfig,
	OverlayMountConfig,
	OverlayRootFilesystemConfig,
	PlainMountConfig,
	ProcessOutput,
	ProcessTreeNode,
	ReaddirEntry,
	ReaddirRecursiveOptions,
	RootFilesystemConfig,
	RootLowerInput,
	ShellData,
	ShellExit,
	ShellOptions,
} from "./agent-os.js";
export type {
	CodeEvaluationResult,
	CodeExecutionResult,
	ContextDescriptor,
	ContextState,
	ExecutionErrorData,
	ExecutionSignal,
	InlineExecutionOptions,
	JavaScriptEvaluationOptions,
	JavaScriptExecutionOptions,
	LanguageExecutionOptions,
	LanguageSpawnOptions,
	NpmPackageInstallOptions,
	NpmProjectInstallOptions,
	OutputCapture,
	OutputReplay,
	ProcessDescriptor,
	ProcessExit,
	ProcessOutputEvent,
	PythonInstallOptions,
	SpawnOptions,
	TypeScriptCheckOptions,
	TypeScriptCheckResult,
	TypeScriptDiagnostic,
	TypeScriptEvaluationOptions,
	TypeScriptExecutionOptions,
	TypeScriptFileExecutionOptions,
} from "./language-execution.js";
export type * from "./session-api.js";
/**
 * An agent type id — the `name` of an `/opt/agentos` agent package manifest
 * (e.g. `"pi"`, `"claude"`). Agents are resolved by the SIDECAR from the projected
 * package manifest (`/opt/agentos/<name>/current/agentos-package.json`); the client
 * passes only the name, so any manifest `name` is a valid agent type.
 */
export type AgentType = string;
export type {
	AgentBlock,
	PackageDescriptor,
	PackageRef,
	SoftwarePackageRef,
} from "./agentos-package.js";
export type {
	CronAction,
	CronActionInfo,
	CronEvent,
	CronEventHandler,
	CronJob,
	CronJobInfo,
	CronJobOptions,
	ScheduleDriver,
	ScheduleEntry,
	ScheduleHandle,
} from "./cron/index.js";
export type {
	HostDirBackendOptions,
	HostDirMountPluginConfig,
	NodeModulesMountConfig,
} from "./host-dir-mount.js";
export type {
	HostFunction,
	HostFunctionCollection,
	HostFunctionCollections,
	HostFunctionExample,
	HostFunctionSchemas,
	ResolvedHostFunctions,
} from "@rivet-dev/agentos-runtime-core/host-functions";
export type {
	FilesystemSnapshotExport,
	LayerHandle,
	LayerStore,
	OverlayFilesystemMode,
	RootSnapshotExport,
	SnapshotImportSource,
	SnapshotLayerHandle,
	WritableLayerHandle,
} from "./layers.js";
export type { SoftwareInput, SoftwareRoot } from "./packages.js";
export type {
	ChildProcessPermissions,
	ConnectTerminalOptions,
	EnvPermissions,
	ExecOptions,
	ExecResult,
	FsPermissionRule,
	FsPermissions,
	KernelExecOptions,
	KernelExecResult,
	KernelSpawnOptions,
	NetworkAccessRequest,
	NetworkPermissions,
	OpenShellOptions,
	PatternPermissionRule,
	PermissionDecision,
	PermissionMode,
	Permissions,
	ProcessInfo,
	RulePermissions,
	StdioChannel,
	TimingMitigation,
	VirtualDirEntry,
	VirtualFileSystem,
	VirtualStat,
} from "./runtime.js";
export type {
	AgentOsSandboxClient,
	AgentOsSandboxClientOptions,
	AgentOsSandboxCommonOptions,
	AgentOsSandboxInput,
	AgentOsSandboxOptions,
	AgentOsSandboxProcessInfo,
	AgentOsSandboxProcessLogs,
	AgentOsSandboxProcessResult,
	AgentOsSandboxProvider,
	AgentOsSandboxProviderOptions,
	SandboxMountPluginConfig,
} from "./sandbox.js";
