.include "../misc/BSDmakefile.shared"

.PHONY: all
all: test

.PHONY: test
test: $(TEST_RESULTS)

../misc/namespace: ../misc/namespace.c
	$(CC_FOR_BUILD) $(CFLAGS_FOR_BUILD) $(CPPFLAGS_FOR_BUILD) ../misc/namespace.c -o $@ $(LDFLAGS_FOR_BUILD)

.SUFFIXES: .i .c .dM

.c.i:
	$(CC) $(CFLAGS) $(CPPFLAGS) -D_POSIX_C_SOURCE=202405L $(STD_C17) -E $< -o $@ 2>/dev/null || echo missing_header > $@

.c.dM:
	$(CC) $(CFLAGS) $(CPPFLAGS) -D_POSIX_C_SOURCE=202405L $(STD_C17) -E -dM $< -o $@ 2>/dev/null || echo missing_header > $@

.for TEST in $(TEST_SOURCES)
$(OUT_PATH)/$(TEST:.c=.out): $(TEST:.c=.i) $(TEST:.c=.dM) ../misc/namespace
.if "$(TEST:-xsi.c=.c)" == "$(TEST)"
	../misc/namespace -o $@ -e $(@:.out=.err) -I ../include -i $(TEST:.c=) $(TEST:.c=.i) $(TEST:.c=.dM)
.else
	../misc/namespace -o $@ -e $(@:.out=.err) -I ../include -i $(TEST:-xsi.c=) -x $(TEST:.c=.i) $(TEST:.c=.dM)
.endif
.endfor

.PHONY: clean
clean: clean-test
	rm -f *.i *.dM *.tmp
	rm -f ../misc/namespace

.PHONY: clean-test
clean-test:
	rm -rf $(OUT_PATH)
