.include "../misc/BSDmakefile.shared"

.PHONY: all
all: $(TESTS)

.c:
	../misc/compile.sh "$(CC) $(CFLAGS) $(CPPFLAGS)" $* "$(LDFLAGS)" "$(EXTRA_LDFLAGS)" "$(OS)" "$(OUT_PATH)"

.PHONY: test
test: $(TEST_RESULTS)

.for TEST in $(TEST_SOURCES)
$(OUT_PATH)/$(TEST:.c=.out): $(TEST:.c=)
	../misc/run.sh $(TEST:.c=) $@
.endfor

.PHONY: clean
clean: clean-test
	rm -f $(TESTS)

.PHONY: clean-test
clean-test:
	rm -rf $(OUT_PATH)
