include ../misc/GNUmakefile.shared

.PHONY: all
all: $(TESTS)

.c:
	../misc/compile.sh "$(CC) $(CFLAGS) $(CPPFLAGS)" $* "$(LDFLAGS)" "$(EXTRA_LDFLAGS)" "$(OS)" "$(OUT_PATH)"

.PHONY: test
test: $(TEST_RESULTS)

$(OUT_PATH):
	mkdir -p $(OUT_PATH)

$(OUT_PATH)/%.out: %
	../misc/run.sh $* $@

.PHONY: clean
clean: clean-test
	rm -f $(TESTS)

.PHONY: clean-test
clean-test:
	rm -rf $(OUT_PATH)
