/* Test whether a basic cosl invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)

// Soft fail on rounding errors and report only one.
int imprecise;

static const char* fperrname(int excepts)
{
	switch ( excepts )
	{
	case 0: return "FE_NONE";
	case FE_INVALID: return "FE_INVALID";
	case FE_DIVBYZERO: return "FE_DIVBYZERO";
	case FE_OVERFLOW: return "FE_OVERFLOW";
	case FE_UNDERFLOW: return "FE_UNDERFLOW";
	default: return "FE_MULTIPLE";
	}
}

void test(int variant, long double input1, int errnum, int fperr, long double lower, long double expected, long double upper, int flags)
{
	errno = 0;
	if ( feclearexcept(FE_ALL_EXCEPT) )
		errx(1, "feclearexcept");
	long double output = cosl(input1);
	if ( errnum == 0 && errno )
		err(1, "(%d.) cosl(%.4Lf) failed",
                    variant, input1);
	if ( (math_errhandling & MATH_ERRNO) && errnum && errno != errnum )
		errx(1, "(%d.) cosl(%.4Lf) did not %s",
                     variant, input1, strerrno(errnum));
	int excepts = fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
	if ( fperr == 0 && excepts )
		errx(1, "(%d.) cosl(%.4Lf) %s",
                     variant, input1, fperrname(excepts));
	if ( (math_errhandling & MATH_ERREXCEPT) && fperr != 0 &&
	     excepts != fperr && !((flags & MF_MAYERR) && !excepts) )
		errx(1, "(%d.) cosl(%.4Lf) did not %s",
                     variant, input1, fperrname(fperr));
	if ( !(flags & MF_UNSPEC1) )
	{
		if ( !(isnan(expected) ? isnan(output) :
		       isfinite(expected) && expected != 0.0 ?
		       isfinite(output) && (output == expected || (lower < output && output < upper)) :
		       output == expected) )
		{
			if ( imprecise && isfinite(output) && isfinite(expected) )
				return;
			warnx("(%d.) cosl(%.4Lf) = %.17La, not %.17La, diff %.17La, ratio %.20Lg",
			     variant, input1, output, expected,
			     output - expected, output / expected);
			if ( !isfinite(output) || !isfinite(expected) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, 90.01, 0, 0, -0xe.9faba732b9cf9dep-5L, -0xe.9faba732b9cf9ddp-5L, -0xe.9faba732b9cf9dcp-5L, 0);
	test(2, -12.34, 0, 0, 0xf.97801940f69bf73p-4L, 0xf.97801940f69bf74p-4L, 0xf.97801940f69bf75p-4L, 0);
	test(3, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(4, strtold("inf", NULL), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(5, strtold("-inf", NULL), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(6, 0.0, 0, 0, 0xf.fffffffffffffffp-4L, 0x8.0p-3L, 0x8.000000000000001p-3L, 0);
	return imprecise;
}
