/* Test whether a basic fmaf invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)

// Soft fail on rounding errors and report only one.
int imprecise;

static const char* fperrname(int excepts)
{
	switch ( excepts )
	{
	case 0: return "FE_NONE";
	case FE_INVALID: return "FE_INVALID";
	case FE_DIVBYZERO: return "FE_DIVBYZERO";
	case FE_OVERFLOW: return "FE_OVERFLOW";
	case FE_UNDERFLOW: return "FE_UNDERFLOW";
	default: return "FE_MULTIPLE";
	}
}

void test(int variant, float input1, float input2, float input3, int errnum, int fperr, float lower, float expected, float upper, int flags)
{
	errno = 0;
	if ( feclearexcept(FE_ALL_EXCEPT) )
		errx(1, "feclearexcept");
	float output = fmaf(input1, input2, input3);
	if ( errnum == 0 && errno )
		err(1, "(%d.) fmaf(%.4f, %.4f, %.4f) failed",
                    variant, input1, input2, input3);
	if ( (math_errhandling & MATH_ERRNO) && errnum && errno != errnum )
		errx(1, "(%d.) fmaf(%.4f, %.4f, %.4f) did not %s",
                     variant, input1, input2, input3, strerrno(errnum));
	int excepts = fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
	if ( fperr == 0 && excepts )
		errx(1, "(%d.) fmaf(%.4f, %.4f, %.4f) %s",
                     variant, input1, input2, input3, fperrname(excepts));
	if ( (math_errhandling & MATH_ERREXCEPT) && fperr != 0 &&
	     excepts != fperr && !((flags & MF_MAYERR) && !excepts) )
		errx(1, "(%d.) fmaf(%.4f, %.4f, %.4f) did not %s",
                     variant, input1, input2, input3, fperrname(fperr));
	if ( !(flags & MF_UNSPEC1) )
	{
		if ( !(isnan(expected) ? isnan(output) :
		       isfinite(expected) && expected != 0.0 ?
		       isfinite(output) && (output == expected || (lower < output && output < upper)) :
		       output == expected) )
		{
			if ( imprecise && isfinite(output) && isfinite(expected) )
				return;
			warnx("(%d.) fmaf(%.4f, %.4f, %.4f) = %.6a, not %.6a, diff %.6a, ratio %.8g",
			     variant, input1, input2, input3, output, expected,
			     output - expected, output / expected);
			if ( !isfinite(output) || !isfinite(expected) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, 90.01, 13.37, 10.1, 0, 0, 0x1.2f6226p+10, 0x1.2f6228p+10, 0x1.2f622ap+10, 0);
	test(2, -12.34, 13.37, 10.1, 0, 0, -0x1.35c58ap+7, -0x1.35c588p+7, -0x1.35c586p+7, 0);
	test(3, nanf(""), 13.37, 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(4, strtof("inf", NULL), 13.37, 10.1, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(5, strtof("-inf", NULL), 13.37, 10.1, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(6, 0.0, 13.37, 10.1, 0, 0, 0x1.433332p+3, 0x1.433334p+3, 0x1.433336p+3, 0);
	test(7, 90.01, -12.34, 10.1, 0, 0, -0x1.1327e8p+10, -0x1.1327e6p+10, -0x1.1327e4p+10, 0);
	test(8, -12.34, -12.34, 10.1, 0, 0, 0x1.44c04ep+7, 0x1.44c05p+7, 0x1.44c052p+7, 0);
	test(9, nanf(""), -12.34, 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(10, strtof("inf", NULL), -12.34, 10.1, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(11, strtof("-inf", NULL), -12.34, 10.1, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(12, 0.0, -12.34, 10.1, 0, 0, 0x1.433332p+3, 0x1.433334p+3, 0x1.433336p+3, 0);
	test(13, 90.01, nanf(""), 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(14, -12.34, nanf(""), 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(15, nanf(""), nanf(""), 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(16, strtof("inf", NULL), nanf(""), 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(17, strtof("-inf", NULL), nanf(""), 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(18, 0.0, nanf(""), 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(19, 90.01, strtof("inf", NULL), 10.1, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(20, -12.34, strtof("inf", NULL), 10.1, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(21, nanf(""), strtof("inf", NULL), 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(22, strtof("inf", NULL), strtof("inf", NULL), 10.1, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(23, strtof("-inf", NULL), strtof("inf", NULL), 10.1, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(24, 0.0, strtof("inf", NULL), 10.1, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(25, 90.01, strtof("-inf", NULL), 10.1, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(26, -12.34, strtof("-inf", NULL), 10.1, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(27, nanf(""), strtof("-inf", NULL), 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(28, strtof("inf", NULL), strtof("-inf", NULL), 10.1, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(29, strtof("-inf", NULL), strtof("-inf", NULL), 10.1, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(30, 0.0, strtof("-inf", NULL), 10.1, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(31, 90.01, 0.0, 10.1, 0, 0, 0x1.433332p+3, 0x1.433334p+3, 0x1.433336p+3, 0);
	test(32, -12.34, 0.0, 10.1, 0, 0, 0x1.433332p+3, 0x1.433334p+3, 0x1.433336p+3, 0);
	test(33, nanf(""), 0.0, 10.1, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(34, strtof("inf", NULL), 0.0, 10.1, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(35, strtof("-inf", NULL), 0.0, 10.1, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(36, 0.0, 0.0, 10.1, 0, 0, 0x1.433332p+3, 0x1.433334p+3, 0x1.433336p+3, 0);
	test(37, 90.01, 13.37, -12.34, 0, 0, 0x1.29c5fep+10, 0x1.29c6p+10, 0x1.29c602p+10, 0);
	test(38, -12.34, 13.37, -12.34, 0, 0, -0x1.62a6d2p+7, -0x1.62a6dp+7, -0x1.62a6cep+7, 0);
	test(39, nanf(""), 13.37, -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(40, strtof("inf", NULL), 13.37, -12.34, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(41, strtof("-inf", NULL), 13.37, -12.34, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(42, 0.0, 13.37, -12.34, 0, 0, -0x1.8ae14ap+3, -0x1.8ae148p+3, -0x1.8ae146p+3, 0);
	test(43, 90.01, -12.34, -12.34, 0, 0, -0x1.18c412p+10, -0x1.18c41p+10, -0x1.18c40ep+10, 0);
	test(44, -12.34, -12.34, -12.34, 0, 0, 0x1.17df06p+7, 0x1.17df08p+7, 0x1.17df0ap+7, 0);
	test(45, nanf(""), -12.34, -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(46, strtof("inf", NULL), -12.34, -12.34, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(47, strtof("-inf", NULL), -12.34, -12.34, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(48, 0.0, -12.34, -12.34, 0, 0, -0x1.8ae14ap+3, -0x1.8ae148p+3, -0x1.8ae146p+3, 0);
	test(49, 90.01, nanf(""), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(50, -12.34, nanf(""), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(51, nanf(""), nanf(""), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(52, strtof("inf", NULL), nanf(""), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(53, strtof("-inf", NULL), nanf(""), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(54, 0.0, nanf(""), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(55, 90.01, strtof("inf", NULL), -12.34, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(56, -12.34, strtof("inf", NULL), -12.34, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(57, nanf(""), strtof("inf", NULL), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(58, strtof("inf", NULL), strtof("inf", NULL), -12.34, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(59, strtof("-inf", NULL), strtof("inf", NULL), -12.34, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(60, 0.0, strtof("inf", NULL), -12.34, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(61, 90.01, strtof("-inf", NULL), -12.34, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(62, -12.34, strtof("-inf", NULL), -12.34, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(63, nanf(""), strtof("-inf", NULL), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(64, strtof("inf", NULL), strtof("-inf", NULL), -12.34, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(65, strtof("-inf", NULL), strtof("-inf", NULL), -12.34, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(66, 0.0, strtof("-inf", NULL), -12.34, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(67, 90.01, 0.0, -12.34, 0, 0, -0x1.8ae14ap+3, -0x1.8ae148p+3, -0x1.8ae146p+3, 0);
	test(68, -12.34, 0.0, -12.34, 0, 0, -0x1.8ae14ap+3, -0x1.8ae148p+3, -0x1.8ae146p+3, 0);
	test(69, nanf(""), 0.0, -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(70, strtof("inf", NULL), 0.0, -12.34, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(71, strtof("-inf", NULL), 0.0, -12.34, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(72, 0.0, 0.0, -12.34, 0, 0, -0x1.8ae14ap+3, -0x1.8ae148p+3, -0x1.8ae146p+3, 0);
	test(73, 90.01, 13.37, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(74, -12.34, 13.37, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(75, nanf(""), 13.37, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(76, strtof("inf", NULL), 13.37, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(77, strtof("-inf", NULL), 13.37, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(78, 0.0, 13.37, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(79, 90.01, -12.34, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(80, -12.34, -12.34, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(81, nanf(""), -12.34, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(82, strtof("inf", NULL), -12.34, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(83, strtof("-inf", NULL), -12.34, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(84, 0.0, -12.34, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(85, 90.01, nanf(""), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(86, -12.34, nanf(""), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(87, nanf(""), nanf(""), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(88, strtof("inf", NULL), nanf(""), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(89, strtof("-inf", NULL), nanf(""), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(90, 0.0, nanf(""), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(91, 90.01, strtof("inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(92, -12.34, strtof("inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(93, nanf(""), strtof("inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(94, strtof("inf", NULL), strtof("inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(95, strtof("-inf", NULL), strtof("inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(96, 0.0, strtof("inf", NULL), nanf(""), EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0 | MF_MAYERR);
	test(97, 90.01, strtof("-inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(98, -12.34, strtof("-inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(99, nanf(""), strtof("-inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(100, strtof("inf", NULL), strtof("-inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(101, strtof("-inf", NULL), strtof("-inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(102, 0.0, strtof("-inf", NULL), nanf(""), EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0 | MF_MAYERR);
	test(103, 90.01, 0.0, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(104, -12.34, 0.0, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(105, nanf(""), 0.0, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(106, strtof("inf", NULL), 0.0, nanf(""), EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0 | MF_MAYERR);
	test(107, strtof("-inf", NULL), 0.0, nanf(""), EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0 | MF_MAYERR);
	test(108, 0.0, 0.0, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(109, 90.01, 13.37, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(110, -12.34, 13.37, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(111, nanf(""), 13.37, strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(112, strtof("inf", NULL), 13.37, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(113, strtof("-inf", NULL), 13.37, strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(114, 0.0, 13.37, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(115, 90.01, -12.34, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(116, -12.34, -12.34, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(117, nanf(""), -12.34, strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(118, strtof("inf", NULL), -12.34, strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(119, strtof("-inf", NULL), -12.34, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(120, 0.0, -12.34, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(121, 90.01, nanf(""), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(122, -12.34, nanf(""), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(123, nanf(""), nanf(""), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(124, strtof("inf", NULL), nanf(""), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(125, strtof("-inf", NULL), nanf(""), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(126, 0.0, nanf(""), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(127, 90.01, strtof("inf", NULL), strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(128, -12.34, strtof("inf", NULL), strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(129, nanf(""), strtof("inf", NULL), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(130, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(131, strtof("-inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(132, 0.0, strtof("inf", NULL), strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(133, 90.01, strtof("-inf", NULL), strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(134, -12.34, strtof("-inf", NULL), strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(135, nanf(""), strtof("-inf", NULL), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(136, strtof("inf", NULL), strtof("-inf", NULL), strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(137, strtof("-inf", NULL), strtof("-inf", NULL), strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(138, 0.0, strtof("-inf", NULL), strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(139, 90.01, 0.0, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(140, -12.34, 0.0, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(141, nanf(""), 0.0, strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(142, strtof("inf", NULL), 0.0, strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(143, strtof("-inf", NULL), 0.0, strtof("inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(144, 0.0, 0.0, strtof("inf", NULL), 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(145, 90.01, 13.37, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(146, -12.34, 13.37, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(147, nanf(""), 13.37, strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(148, strtof("inf", NULL), 13.37, strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(149, strtof("-inf", NULL), 13.37, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(150, 0.0, 13.37, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(151, 90.01, -12.34, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(152, -12.34, -12.34, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(153, nanf(""), -12.34, strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(154, strtof("inf", NULL), -12.34, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(155, strtof("-inf", NULL), -12.34, strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(156, 0.0, -12.34, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(157, 90.01, nanf(""), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(158, -12.34, nanf(""), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(159, nanf(""), nanf(""), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(160, strtof("inf", NULL), nanf(""), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(161, strtof("-inf", NULL), nanf(""), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(162, 0.0, nanf(""), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(163, 90.01, strtof("inf", NULL), strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(164, -12.34, strtof("inf", NULL), strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(165, nanf(""), strtof("inf", NULL), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(166, strtof("inf", NULL), strtof("inf", NULL), strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(167, strtof("-inf", NULL), strtof("inf", NULL), strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(168, 0.0, strtof("inf", NULL), strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(169, 90.01, strtof("-inf", NULL), strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(170, -12.34, strtof("-inf", NULL), strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(171, nanf(""), strtof("-inf", NULL), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(172, strtof("inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(173, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(174, 0.0, strtof("-inf", NULL), strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(175, 90.01, 0.0, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(176, -12.34, 0.0, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(177, nanf(""), 0.0, strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(178, strtof("inf", NULL), 0.0, strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(179, strtof("-inf", NULL), 0.0, strtof("-inf", NULL), 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(180, 0.0, 0.0, strtof("-inf", NULL), 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(181, 90.01, 13.37, 0.0, 0, 0, 0x1.2cdbcp+10, 0x1.2cdbc2p+10, 0x1.2cdbc4p+10, 0);
	test(182, -12.34, 13.37, 0.0, 0, 0, -0x1.49f8bcp+7, -0x1.49f8bap+7, -0x1.49f8b8p+7, 0);
	test(183, nanf(""), 13.37, 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(184, strtof("inf", NULL), 13.37, 0.0, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(185, strtof("-inf", NULL), 13.37, 0.0, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(186, 0.0, 13.37, 0.0, 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	test(187, 90.01, -12.34, 0.0, 0, 0, -0x1.15ae4ep+10, -0x1.15ae4cp+10, -0x1.15ae4ap+10, 0);
	test(188, -12.34, -12.34, 0.0, 0, 0, 0x1.308d1ap+7, 0x1.308d1cp+7, 0x1.308d1ep+7, 0);
	test(189, nanf(""), -12.34, 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(190, strtof("inf", NULL), -12.34, 0.0, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(191, strtof("-inf", NULL), -12.34, 0.0, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(192, 0.0, -12.34, 0.0, 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	test(193, 90.01, nanf(""), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(194, -12.34, nanf(""), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(195, nanf(""), nanf(""), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(196, strtof("inf", NULL), nanf(""), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(197, strtof("-inf", NULL), nanf(""), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(198, 0.0, nanf(""), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(199, 90.01, strtof("inf", NULL), 0.0, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(200, -12.34, strtof("inf", NULL), 0.0, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(201, nanf(""), strtof("inf", NULL), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(202, strtof("inf", NULL), strtof("inf", NULL), 0.0, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(203, strtof("-inf", NULL), strtof("inf", NULL), 0.0, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(204, 0.0, strtof("inf", NULL), 0.0, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(205, 90.01, strtof("-inf", NULL), 0.0, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(206, -12.34, strtof("-inf", NULL), 0.0, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(207, nanf(""), strtof("-inf", NULL), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(208, strtof("inf", NULL), strtof("-inf", NULL), 0.0, 0, 0, strtof("-inf", NULL), strtof("-inf", NULL), strtof("-inf", NULL), 0);
	test(209, strtof("-inf", NULL), strtof("-inf", NULL), 0.0, 0, 0, strtof("inf", NULL), strtof("inf", NULL), strtof("inf", NULL), 0);
	test(210, 0.0, strtof("-inf", NULL), 0.0, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(211, 90.01, 0.0, 0.0, 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	test(212, -12.34, 0.0, 0.0, 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	test(213, nanf(""), 0.0, 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(214, strtof("inf", NULL), 0.0, 0.0, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(215, strtof("-inf", NULL), 0.0, 0.0, 0, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(216, 0.0, 0.0, 0.0, 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	return imprecise;
}
