/* Test whether a basic fmal invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)

// Soft fail on rounding errors and report only one.
int imprecise;

static const char* fperrname(int excepts)
{
	switch ( excepts )
	{
	case 0: return "FE_NONE";
	case FE_INVALID: return "FE_INVALID";
	case FE_DIVBYZERO: return "FE_DIVBYZERO";
	case FE_OVERFLOW: return "FE_OVERFLOW";
	case FE_UNDERFLOW: return "FE_UNDERFLOW";
	default: return "FE_MULTIPLE";
	}
}

void test(int variant, long double input1, long double input2, long double input3, int errnum, int fperr, long double lower, long double expected, long double upper, int flags)
{
	errno = 0;
	if ( feclearexcept(FE_ALL_EXCEPT) )
		errx(1, "feclearexcept");
	long double output = fmal(input1, input2, input3);
	if ( errnum == 0 && errno )
		err(1, "(%d.) fmal(%.4Lf, %.4Lf, %.4Lf) failed",
                    variant, input1, input2, input3);
	if ( (math_errhandling & MATH_ERRNO) && errnum && errno != errnum )
		errx(1, "(%d.) fmal(%.4Lf, %.4Lf, %.4Lf) did not %s",
                     variant, input1, input2, input3, strerrno(errnum));
	int excepts = fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
	if ( fperr == 0 && excepts )
		errx(1, "(%d.) fmal(%.4Lf, %.4Lf, %.4Lf) %s",
                     variant, input1, input2, input3, fperrname(excepts));
	if ( (math_errhandling & MATH_ERREXCEPT) && fperr != 0 &&
	     excepts != fperr && !((flags & MF_MAYERR) && !excepts) )
		errx(1, "(%d.) fmal(%.4Lf, %.4Lf, %.4Lf) did not %s",
                     variant, input1, input2, input3, fperrname(fperr));
	if ( !(flags & MF_UNSPEC1) )
	{
		if ( !(isnan(expected) ? isnan(output) :
		       isfinite(expected) && expected != 0.0 ?
		       isfinite(output) && (output == expected || (lower < output && output < upper)) :
		       output == expected) )
		{
			if ( imprecise && isfinite(output) && isfinite(expected) )
				return;
			warnx("(%d.) fmal(%.4Lf, %.4Lf, %.4Lf) = %.17La, not %.17La, diff %.17La, ratio %.20Lg",
			     variant, input1, input2, input3, output, expected,
			     output - expected, output / expected);
			if ( !isfinite(output) || !isfinite(expected) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, 90.01, 13.37, 10.1, 0, 0, 0x9.7b1141205bc018ep+7L, 0x9.7b1141205bc018fp+7L, 0x9.7b1141205bc019p+7L, 0);
	test(2, -12.34, 13.37, 10.1, 0, 0, -0x9.ae2c3c9eecbf7fp+4L, -0x9.ae2c3c9eecbf7efp+4L, -0x9.ae2c3c9eecbf7eep+4L, 0);
	test(3, nanl(""), 13.37, 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(4, strtold("inf", NULL), 13.37, 10.1, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(5, strtold("-inf", NULL), 13.37, 10.1, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(6, 0.0, 13.37, 10.1, 0, 0, 0xa.1999999999997ffp+0L, 0xa.1999999999998p+0L, 0xa.199999999999801p+0L, 0);
	test(7, 90.01, -12.34, 10.1, 0, 0, -0x8.993f2e48e8a73a8p+7L, -0x8.993f2e48e8a73a7p+7L, -0x8.993f2e48e8a73a6p+7L, 0);
	test(8, -12.34, -12.34, 10.1, 0, 0, 0xa.26027525460a94dp+4L, 0xa.26027525460a94ep+4L, 0xa.26027525460a94fp+4L, 0);
	test(9, nanl(""), -12.34, 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(10, strtold("inf", NULL), -12.34, 10.1, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(11, strtold("-inf", NULL), -12.34, 10.1, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(12, 0.0, -12.34, 10.1, 0, 0, 0xa.1999999999997ffp+0L, 0xa.1999999999998p+0L, 0xa.199999999999801p+0L, 0);
	test(13, 90.01, nanl(""), 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(14, -12.34, nanl(""), 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(15, nanl(""), nanl(""), 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(16, strtold("inf", NULL), nanl(""), 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(17, strtold("-inf", NULL), nanl(""), 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(18, 0.0, nanl(""), 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(19, 90.01, strtold("inf", NULL), 10.1, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(20, -12.34, strtold("inf", NULL), 10.1, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(21, nanl(""), strtold("inf", NULL), 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(22, strtold("inf", NULL), strtold("inf", NULL), 10.1, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(23, strtold("-inf", NULL), strtold("inf", NULL), 10.1, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(24, 0.0, strtold("inf", NULL), 10.1, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(25, 90.01, strtold("-inf", NULL), 10.1, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(26, -12.34, strtold("-inf", NULL), 10.1, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(27, nanl(""), strtold("-inf", NULL), 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(28, strtold("inf", NULL), strtold("-inf", NULL), 10.1, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(29, strtold("-inf", NULL), strtold("-inf", NULL), 10.1, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(30, 0.0, strtold("-inf", NULL), 10.1, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(31, 90.01, 0.0, 10.1, 0, 0, 0xa.1999999999997ffp+0L, 0xa.1999999999998p+0L, 0xa.199999999999801p+0L, 0);
	test(32, -12.34, 0.0, 10.1, 0, 0, 0xa.1999999999997ffp+0L, 0xa.1999999999998p+0L, 0xa.199999999999801p+0L, 0);
	test(33, nanl(""), 0.0, 10.1, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(34, strtold("inf", NULL), 0.0, 10.1, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(35, strtold("-inf", NULL), 0.0, 10.1, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(36, 0.0, 0.0, 10.1, 0, 0, 0xa.1999999999997ffp+0L, 0xa.1999999999998p+0L, 0xa.199999999999801p+0L, 0);
	test(37, 90.01, 13.37, -12.34, 0, 0, 0x9.4e2ff972474537ep+7L, 0x9.4e2ff972474537fp+7L, 0x9.4e2ff972474538p+7L, 0);
	test(38, -12.34, 13.37, -12.34, 0, 0, -0xb.15367a0f909687p+4L, -0xb.15367a0f909686fp+4L, -0xb.15367a0f909686ep+4L, 0);
	test(39, nanl(""), 13.37, -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(40, strtold("inf", NULL), 13.37, -12.34, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(41, strtold("-inf", NULL), 13.37, -12.34, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(42, 0.0, 13.37, -12.34, 0, 0, -0xc.570a3d70a3d7001p+0L, -0xc.570a3d70a3d7p+0L, -0xc.570a3d70a3d6fffp+0L, 0);
	test(43, 90.01, -12.34, -12.34, 0, 0, -0x8.c62075f6fd221b8p+7L, -0x8.c62075f6fd221b7p+7L, -0x8.c62075f6fd221b6p+7L, 0);
	test(44, -12.34, -12.34, -12.34, 0, 0, 0x8.bef837b4a2338cdp+4L, 0x8.bef837b4a2338cep+4L, 0x8.bef837b4a2338cfp+4L, 0);
	test(45, nanl(""), -12.34, -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(46, strtold("inf", NULL), -12.34, -12.34, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(47, strtold("-inf", NULL), -12.34, -12.34, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(48, 0.0, -12.34, -12.34, 0, 0, -0xc.570a3d70a3d7001p+0L, -0xc.570a3d70a3d7p+0L, -0xc.570a3d70a3d6fffp+0L, 0);
	test(49, 90.01, nanl(""), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(50, -12.34, nanl(""), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(51, nanl(""), nanl(""), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(52, strtold("inf", NULL), nanl(""), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(53, strtold("-inf", NULL), nanl(""), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(54, 0.0, nanl(""), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(55, 90.01, strtold("inf", NULL), -12.34, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(56, -12.34, strtold("inf", NULL), -12.34, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(57, nanl(""), strtold("inf", NULL), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(58, strtold("inf", NULL), strtold("inf", NULL), -12.34, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(59, strtold("-inf", NULL), strtold("inf", NULL), -12.34, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(60, 0.0, strtold("inf", NULL), -12.34, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(61, 90.01, strtold("-inf", NULL), -12.34, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(62, -12.34, strtold("-inf", NULL), -12.34, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(63, nanl(""), strtold("-inf", NULL), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(64, strtold("inf", NULL), strtold("-inf", NULL), -12.34, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(65, strtold("-inf", NULL), strtold("-inf", NULL), -12.34, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(66, 0.0, strtold("-inf", NULL), -12.34, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(67, 90.01, 0.0, -12.34, 0, 0, -0xc.570a3d70a3d7001p+0L, -0xc.570a3d70a3d7p+0L, -0xc.570a3d70a3d6fffp+0L, 0);
	test(68, -12.34, 0.0, -12.34, 0, 0, -0xc.570a3d70a3d7001p+0L, -0xc.570a3d70a3d7p+0L, -0xc.570a3d70a3d6fffp+0L, 0);
	test(69, nanl(""), 0.0, -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(70, strtold("inf", NULL), 0.0, -12.34, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(71, strtold("-inf", NULL), 0.0, -12.34, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(72, 0.0, 0.0, -12.34, 0, 0, -0xc.570a3d70a3d7001p+0L, -0xc.570a3d70a3d7p+0L, -0xc.570a3d70a3d6fffp+0L, 0);
	test(73, 90.01, 13.37, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(74, -12.34, 13.37, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(75, nanl(""), 13.37, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(76, strtold("inf", NULL), 13.37, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(77, strtold("-inf", NULL), 13.37, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(78, 0.0, 13.37, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(79, 90.01, -12.34, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(80, -12.34, -12.34, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(81, nanl(""), -12.34, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(82, strtold("inf", NULL), -12.34, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(83, strtold("-inf", NULL), -12.34, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(84, 0.0, -12.34, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(85, 90.01, nanl(""), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(86, -12.34, nanl(""), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(87, nanl(""), nanl(""), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(88, strtold("inf", NULL), nanl(""), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(89, strtold("-inf", NULL), nanl(""), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(90, 0.0, nanl(""), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(91, 90.01, strtold("inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(92, -12.34, strtold("inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(93, nanl(""), strtold("inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(94, strtold("inf", NULL), strtold("inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(95, strtold("-inf", NULL), strtold("inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(96, 0.0, strtold("inf", NULL), nanl(""), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0 | MF_MAYERR);
	test(97, 90.01, strtold("-inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(98, -12.34, strtold("-inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(99, nanl(""), strtold("-inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(100, strtold("inf", NULL), strtold("-inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(101, strtold("-inf", NULL), strtold("-inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(102, 0.0, strtold("-inf", NULL), nanl(""), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0 | MF_MAYERR);
	test(103, 90.01, 0.0, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(104, -12.34, 0.0, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(105, nanl(""), 0.0, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(106, strtold("inf", NULL), 0.0, nanl(""), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0 | MF_MAYERR);
	test(107, strtold("-inf", NULL), 0.0, nanl(""), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0 | MF_MAYERR);
	test(108, 0.0, 0.0, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(109, 90.01, 13.37, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(110, -12.34, 13.37, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(111, nanl(""), 13.37, strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(112, strtold("inf", NULL), 13.37, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(113, strtold("-inf", NULL), 13.37, strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(114, 0.0, 13.37, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(115, 90.01, -12.34, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(116, -12.34, -12.34, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(117, nanl(""), -12.34, strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(118, strtold("inf", NULL), -12.34, strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(119, strtold("-inf", NULL), -12.34, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(120, 0.0, -12.34, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(121, 90.01, nanl(""), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(122, -12.34, nanl(""), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(123, nanl(""), nanl(""), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(124, strtold("inf", NULL), nanl(""), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(125, strtold("-inf", NULL), nanl(""), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(126, 0.0, nanl(""), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(127, 90.01, strtold("inf", NULL), strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(128, -12.34, strtold("inf", NULL), strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(129, nanl(""), strtold("inf", NULL), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(130, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(131, strtold("-inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(132, 0.0, strtold("inf", NULL), strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(133, 90.01, strtold("-inf", NULL), strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(134, -12.34, strtold("-inf", NULL), strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(135, nanl(""), strtold("-inf", NULL), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(136, strtold("inf", NULL), strtold("-inf", NULL), strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(137, strtold("-inf", NULL), strtold("-inf", NULL), strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(138, 0.0, strtold("-inf", NULL), strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(139, 90.01, 0.0, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(140, -12.34, 0.0, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(141, nanl(""), 0.0, strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(142, strtold("inf", NULL), 0.0, strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(143, strtold("-inf", NULL), 0.0, strtold("inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(144, 0.0, 0.0, strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(145, 90.01, 13.37, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(146, -12.34, 13.37, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(147, nanl(""), 13.37, strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(148, strtold("inf", NULL), 13.37, strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(149, strtold("-inf", NULL), 13.37, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(150, 0.0, 13.37, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(151, 90.01, -12.34, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(152, -12.34, -12.34, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(153, nanl(""), -12.34, strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(154, strtold("inf", NULL), -12.34, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(155, strtold("-inf", NULL), -12.34, strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(156, 0.0, -12.34, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(157, 90.01, nanl(""), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(158, -12.34, nanl(""), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(159, nanl(""), nanl(""), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(160, strtold("inf", NULL), nanl(""), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(161, strtold("-inf", NULL), nanl(""), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(162, 0.0, nanl(""), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(163, 90.01, strtold("inf", NULL), strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(164, -12.34, strtold("inf", NULL), strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(165, nanl(""), strtold("inf", NULL), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(166, strtold("inf", NULL), strtold("inf", NULL), strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(167, strtold("-inf", NULL), strtold("inf", NULL), strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(168, 0.0, strtold("inf", NULL), strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(169, 90.01, strtold("-inf", NULL), strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(170, -12.34, strtold("-inf", NULL), strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(171, nanl(""), strtold("-inf", NULL), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(172, strtold("inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(173, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(174, 0.0, strtold("-inf", NULL), strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(175, 90.01, 0.0, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(176, -12.34, 0.0, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(177, nanl(""), 0.0, strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(178, strtold("inf", NULL), 0.0, strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(179, strtold("-inf", NULL), 0.0, strtold("-inf", NULL), 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(180, 0.0, 0.0, strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(181, 90.01, 13.37, 0.0, 0, 0, 0x9.66de0ded288ce5ep+7L, 0x9.66de0ded288ce5fp+7L, 0x9.66de0ded288ce6p+7L, 0);
	test(182, -12.34, 13.37, 0.0, 0, 0, -0xa.4fc5d638865917p+4L, -0xa.4fc5d638865916fp+4L, -0xa.4fc5d638865916ep+4L, 0);
	test(183, nanl(""), 13.37, 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(184, strtold("inf", NULL), 13.37, 0.0, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(185, strtold("-inf", NULL), 13.37, 0.0, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(186, 0.0, 13.37, 0.0, 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(187, 90.01, -12.34, 0.0, 0, 0, -0x8.ad72617c1bda6d8p+7L, -0x8.ad72617c1bda6d7p+7L, -0x8.ad72617c1bda6d6p+7L, 0);
	test(188, -12.34, -12.34, 0.0, 0, 0, 0x9.8468db8bac70fcdp+4L, 0x9.8468db8bac70fcep+4L, 0x9.8468db8bac70fcfp+4L, 0);
	test(189, nanl(""), -12.34, 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(190, strtold("inf", NULL), -12.34, 0.0, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(191, strtold("-inf", NULL), -12.34, 0.0, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(192, 0.0, -12.34, 0.0, 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(193, 90.01, nanl(""), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(194, -12.34, nanl(""), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(195, nanl(""), nanl(""), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(196, strtold("inf", NULL), nanl(""), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(197, strtold("-inf", NULL), nanl(""), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(198, 0.0, nanl(""), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(199, 90.01, strtold("inf", NULL), 0.0, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(200, -12.34, strtold("inf", NULL), 0.0, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(201, nanl(""), strtold("inf", NULL), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(202, strtold("inf", NULL), strtold("inf", NULL), 0.0, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(203, strtold("-inf", NULL), strtold("inf", NULL), 0.0, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(204, 0.0, strtold("inf", NULL), 0.0, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(205, 90.01, strtold("-inf", NULL), 0.0, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(206, -12.34, strtold("-inf", NULL), 0.0, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(207, nanl(""), strtold("-inf", NULL), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(208, strtold("inf", NULL), strtold("-inf", NULL), 0.0, 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(209, strtold("-inf", NULL), strtold("-inf", NULL), 0.0, 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(210, 0.0, strtold("-inf", NULL), 0.0, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(211, 90.01, 0.0, 0.0, 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(212, -12.34, 0.0, 0.0, 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(213, nanl(""), 0.0, 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(214, strtold("inf", NULL), 0.0, 0.0, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(215, strtold("-inf", NULL), 0.0, 0.0, 0, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(216, 0.0, 0.0, 0.0, 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	return imprecise;
}
