/* Test whether a basic modf invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)

// Soft fail on rounding errors and report only one.
int imprecise;

static const char* fperrname(int excepts)
{
	switch ( excepts )
	{
	case 0: return "FE_NONE";
	case FE_INVALID: return "FE_INVALID";
	case FE_DIVBYZERO: return "FE_DIVBYZERO";
	case FE_OVERFLOW: return "FE_OVERFLOW";
	case FE_UNDERFLOW: return "FE_UNDERFLOW";
	default: return "FE_MULTIPLE";
	}
}

void test(int variant, double input1, int errnum, int fperr, double lower, double lower_integral, double expected, double expected_integral, double upper, double upper_integral, int flags)
{
	errno = 0;
	if ( feclearexcept(FE_ALL_EXCEPT) )
		errx(1, "feclearexcept");
	double integral;
	double output = modf(input1, &integral);
	if ( errnum == 0 && errno )
		err(1, "(%d.) modf(%.4f) failed",
                    variant, input1);
	if ( (math_errhandling & MATH_ERRNO) && errnum && errno != errnum )
		errx(1, "(%d.) modf(%.4f) did not %s",
                     variant, input1, strerrno(errnum));
	int excepts = fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
	if ( fperr == 0 && excepts )
		errx(1, "(%d.) modf(%.4f) %s",
                     variant, input1, fperrname(excepts));
	if ( (math_errhandling & MATH_ERREXCEPT) && fperr != 0 &&
	     excepts != fperr && !((flags & MF_MAYERR) && !excepts) )
		errx(1, "(%d.) modf(%.4f) did not %s",
                     variant, input1, fperrname(fperr));
	if ( !(flags & MF_UNSPEC1) )
	{
		if ( !(isnan(expected) ? isnan(output) :
		       isfinite(expected) && expected != 0.0 ?
		       isfinite(output) && (output == expected || (lower < output && output < upper)) :
		       output == expected) )
		{
			if ( imprecise && isfinite(output) && isfinite(expected) )
				return;
			warnx("(%d.) modf(%.4f) = %.14a, not %.14a, diff %.14a, ratio %.16g",
			     variant, input1, output, expected,
			     output - expected, output / expected);
			if ( !isfinite(output) || !isfinite(expected) )
				exit(1);
			imprecise = 1;
		}
	}
	if ( !(flags & MF_UNSPEC2) )
	{
		if ( !(isnan(expected_integral) ? isnan(integral) :
		       isfinite(expected_integral) && expected_integral != 0.0 ?
		       isfinite(integral) && (integral == expected_integral || (lower_integral < integral && integral < upper_integral)) :
		       integral == expected_integral) )
		{
			if ( imprecise && isfinite(integral) && isfinite(expected_integral) )
				return;
			warnx("(%d.) modf(%.4f).integral = %.14a, not %.14a, diff %.14a, ratio %.16g",
			     variant, input1, integral, expected_integral,
			     integral - expected_integral, integral / expected_integral);
			if ( !isfinite(integral) || !isfinite(expected_integral) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, 90.01, 0, 0, 0x1.47ae147ae1fffp-7, 0x1.67fffffffffffp+6, 0x1.47ae147ae2p-7, 0x1.68p+6, 0x1.47ae147ae2001p-7, 0x1.6800000000001p+6, 0);
	test(2, -12.34, 0, 0, -0x1.5c28f5c28f5c1p-2, -0x1.8000000000001p+3, -0x1.5c28f5c28f5cp-2, -0x1.8p+3, -0x1.5c28f5c28f5bfp-2, -0x1.7ffffffffffffp+3, 0);
	test(3, nan(""), 0, 0, nan(""), nan(""), nan(""), nan(""), nan(""), nan(""), 0);
	test(4, strtod("inf", NULL), 0, 0, -0x0.0000000000001p-1022, strtod("inf", NULL), 0x0.0p+0, strtod("inf", NULL), 0x0.0000000000001p-1022, strtod("inf", NULL), 0);
	test(5, strtod("-inf", NULL), 0, 0, -0x0.0000000000001p-1022, strtod("-inf", NULL), -0x0.0p+0, strtod("-inf", NULL), 0x0.0000000000001p-1022, strtod("-inf", NULL), 0);
	test(6, 0.0, 0, 0, -0x0.0000000000001p-1022, -0x0.0000000000001p-1022, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0000000000001p-1022, 0);
	return imprecise;
}
