/* Test whether a basic nexttowardl invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <errno.h>
#include <fenv.h>
#include <float.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)

// Soft fail on rounding errors and report only one.
int imprecise;

static const char* fperrname(int excepts)
{
	switch ( excepts )
	{
	case 0: return "FE_NONE";
	case FE_INVALID: return "FE_INVALID";
	case FE_DIVBYZERO: return "FE_DIVBYZERO";
	case FE_OVERFLOW: return "FE_OVERFLOW";
	case FE_UNDERFLOW: return "FE_UNDERFLOW";
	default: return "FE_MULTIPLE";
	}
}

void test(int variant, long double input1, long double input2, int errnum, int fperr, long double lower, long double expected, long double upper, int flags)
{
	errno = 0;
	if ( feclearexcept(FE_ALL_EXCEPT) )
		errx(1, "feclearexcept");
	long double output = nexttowardl(input1, input2);
	if ( errnum == 0 && errno )
		err(1, "(%d.) nexttowardl(%.4Lf, %.4Lf) failed",
                    variant, input1, input2);
	if ( (math_errhandling & MATH_ERRNO) && errnum && errno != errnum )
		errx(1, "(%d.) nexttowardl(%.4Lf, %.4Lf) did not %s",
                     variant, input1, input2, strerrno(errnum));
	int excepts = fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
	if ( fperr == 0 && excepts )
		errx(1, "(%d.) nexttowardl(%.4Lf, %.4Lf) %s",
                     variant, input1, input2, fperrname(excepts));
	if ( (math_errhandling & MATH_ERREXCEPT) && fperr != 0 &&
	     excepts != fperr && !((flags & MF_MAYERR) && !excepts) )
		errx(1, "(%d.) nexttowardl(%.4Lf, %.4Lf) did not %s",
                     variant, input1, input2, fperrname(fperr));
	if ( !(flags & MF_UNSPEC1) )
	{
		if ( !(isnan(expected) ? isnan(output) :
		       isfinite(expected) && expected != 0.0 ?
		       isfinite(output) && (output == expected || (lower < output && output < upper)) :
		       output == expected) )
		{
			if ( imprecise && isfinite(output) && isfinite(expected) )
				return;
			warnx("(%d.) nexttowardl(%.4Lf, %.4Lf) = %.17La, not %.17La, diff %.17La, ratio %.20Lg",
			     variant, input1, input2, output, expected,
			     output - expected, output / expected);
			if ( !isfinite(output) || !isfinite(expected) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, 90.01, 13.37, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d6f0p+6 : 0xb.4051eb851eb87fe00p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d700p+6 : 0xb.4051eb851eb87ff00p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d710p+6 : 0xb.4051eb851eb880000p+3L, 0);
	test(2, -12.34, 13.37, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ae0p+3 : -0xc.570a3d70a3d700000p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ad0p+3 : -0xc.570a3d70a3d6fff00p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ac0p+3 : -0xc.570a3d70a3d6ffe00p+0L, 0);
	test(3, nanl(""), 13.37, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(4, strtold("inf", NULL), 13.37, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.ffffffffffffe0p+1023 : 0xf.ffffffffffffffe00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.fffffffffffff0p+1023 : 0xf.fffffffffffffff00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? strtod("inf", NULL) : strtold("inf", NULL), 0);
	test(5, strtold("-inf", NULL), 13.37, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? strtod("-inf", NULL) : strtold("-inf", NULL), DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.fffffffffffff0p+1023 : -0xf.fffffffffffffff00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.ffffffffffffe0p+1023 : -0xf.ffffffffffffffe00p+16380L, 0);
	test(6, 0.0, 13.37, 0, FE_UNDERFLOW, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x0.00000000000000p+0 : 0x0.00000000000000000p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x0.00000000000010p-1022 : 0x0.00000000000000100p-16385L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x0.00000000000020p-1022 : 0x0.00000000000000200p-16385L, 0);
	test(7, 90.01, -12.34, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d6f0p+6 : 0xb.4051eb851eb87fe00p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d700p+6 : 0xb.4051eb851eb87ff00p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d710p+6 : 0xb.4051eb851eb880000p+3L, 0);
	test(8, -12.34, -12.34, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147af0p+3 : -0xc.570a3d70a3d700100p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ae0p+3 : -0xc.570a3d70a3d700000p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ad0p+3 : -0xc.570a3d70a3d6fff00p+0L, 0);
	test(9, nanl(""), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(10, strtold("inf", NULL), -12.34, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.ffffffffffffe0p+1023 : 0xf.ffffffffffffffe00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.fffffffffffff0p+1023 : 0xf.fffffffffffffff00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? strtod("inf", NULL) : strtold("inf", NULL), 0);
	test(11, strtold("-inf", NULL), -12.34, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? strtod("-inf", NULL) : strtold("-inf", NULL), DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.fffffffffffff0p+1023 : -0xf.fffffffffffffff00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.ffffffffffffe0p+1023 : -0xf.ffffffffffffffe00p+16380L, 0);
	test(12, 0.0, -12.34, 0, FE_UNDERFLOW, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x0.00000000000020p-1022 : -0x0.00000000000000200p-16385L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x0.00000000000010p-1022 : -0x0.00000000000000100p-16385L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x0.00000000000000p+0 : -0x0.00000000000000000p+0L, 0);
	test(13, 90.01, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(14, -12.34, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(15, nanl(""), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(16, strtold("inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(17, strtold("-inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(18, 0.0, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(19, 90.01, strtold("inf", NULL), 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d710p+6 : 0xb.4051eb851eb880000p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d720p+6 : 0xb.4051eb851eb880100p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d730p+6 : 0xb.4051eb851eb880200p+3L, 0);
	test(20, -12.34, strtold("inf", NULL), 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ae0p+3 : -0xc.570a3d70a3d700000p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ad0p+3 : -0xc.570a3d70a3d6fff00p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ac0p+3 : -0xc.570a3d70a3d6ffe00p+0L, 0);
	test(21, nanl(""), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(22, strtold("inf", NULL), strtold("inf", NULL), 0, 0, strtold("inf", NULL), strtold("inf", NULL), strtold("inf", NULL), 0);
	test(23, strtold("-inf", NULL), strtold("inf", NULL), 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? strtod("-inf", NULL) : strtold("-inf", NULL), DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.fffffffffffff0p+1023 : -0xf.fffffffffffffff00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.ffffffffffffe0p+1023 : -0xf.ffffffffffffffe00p+16380L, 0);
	test(24, 0.0, strtold("inf", NULL), 0, FE_UNDERFLOW, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x0.00000000000000p+0 : 0x0.00000000000000000p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x0.00000000000010p-1022 : 0x0.00000000000000100p-16385L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x0.00000000000020p-1022 : 0x0.00000000000000200p-16385L, 0);
	test(25, 90.01, strtold("-inf", NULL), 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d6f0p+6 : 0xb.4051eb851eb87fe00p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d700p+6 : 0xb.4051eb851eb87ff00p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d710p+6 : 0xb.4051eb851eb880000p+3L, 0);
	test(26, -12.34, strtold("-inf", NULL), 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147b00p+3 : -0xc.570a3d70a3d700200p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147af0p+3 : -0xc.570a3d70a3d700100p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ae0p+3 : -0xc.570a3d70a3d700000p+0L, 0);
	test(27, nanl(""), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(28, strtold("inf", NULL), strtold("-inf", NULL), 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.ffffffffffffe0p+1023 : 0xf.ffffffffffffffe00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.fffffffffffff0p+1023 : 0xf.fffffffffffffff00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? strtod("inf", NULL) : strtold("inf", NULL), 0);
	test(29, strtold("-inf", NULL), strtold("-inf", NULL), 0, 0, strtold("-inf", NULL), strtold("-inf", NULL), strtold("-inf", NULL), 0);
	test(30, 0.0, strtold("-inf", NULL), 0, FE_UNDERFLOW, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x0.00000000000020p-1022 : -0x0.00000000000000200p-16385L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x0.00000000000010p-1022 : -0x0.00000000000000100p-16385L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x0.00000000000000p+0 : -0x0.00000000000000000p+0L, 0);
	test(31, 90.01, 0.0, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d6f0p+6 : 0xb.4051eb851eb87fe00p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d700p+6 : 0xb.4051eb851eb87ff00p+3L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.680a3d70a3d710p+6 : 0xb.4051eb851eb880000p+3L, 0);
	test(32, -12.34, 0.0, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ae0p+3 : -0xc.570a3d70a3d700000p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ad0p+3 : -0xc.570a3d70a3d6fff00p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.8ae147ae147ac0p+3 : -0xc.570a3d70a3d6ffe00p+0L, 0);
	test(33, nanl(""), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(34, strtold("inf", NULL), 0.0, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.ffffffffffffe0p+1023 : 0xf.ffffffffffffffe00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x1.fffffffffffff0p+1023 : 0xf.fffffffffffffff00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? strtod("inf", NULL) : strtold("inf", NULL), 0);
	test(35, strtold("-inf", NULL), 0.0, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? strtod("-inf", NULL) : strtold("-inf", NULL), DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.fffffffffffff0p+1023 : -0xf.fffffffffffffff00p+16380L, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x1.ffffffffffffe0p+1023 : -0xf.ffffffffffffffe00p+16380L, 0);
	test(36, 0.0, 0.0, 0, 0, DBL_MANT_DIG == LDBL_MANT_DIG ? -0x0.00000000000010p-1022 : -0x0.00000000000000100p-16385L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x0.00000000000000p+0 : 0x0.00000000000000000p+0L, DBL_MANT_DIG == LDBL_MANT_DIG ? 0x0.00000000000010p-1022 : 0x0.00000000000000100p-16385L, 0);
	return imprecise;
}
