/* Test whether a basic remainderl invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)

// Soft fail on rounding errors and report only one.
int imprecise;

static const char* fperrname(int excepts)
{
	switch ( excepts )
	{
	case 0: return "FE_NONE";
	case FE_INVALID: return "FE_INVALID";
	case FE_DIVBYZERO: return "FE_DIVBYZERO";
	case FE_OVERFLOW: return "FE_OVERFLOW";
	case FE_UNDERFLOW: return "FE_UNDERFLOW";
	default: return "FE_MULTIPLE";
	}
}

void test(int variant, long double input1, long double input2, int errnum, int fperr, long double lower, long double expected, long double upper, int flags)
{
	errno = 0;
	if ( feclearexcept(FE_ALL_EXCEPT) )
		errx(1, "feclearexcept");
	long double output = remainderl(input1, input2);
	if ( errnum == 0 && errno )
		err(1, "(%d.) remainderl(%.4Lf, %.4Lf) failed",
                    variant, input1, input2);
	if ( (math_errhandling & MATH_ERRNO) && errnum && errno != errnum )
		errx(1, "(%d.) remainderl(%.4Lf, %.4Lf) did not %s",
                     variant, input1, input2, strerrno(errnum));
	int excepts = fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
	if ( fperr == 0 && excepts )
		errx(1, "(%d.) remainderl(%.4Lf, %.4Lf) %s",
                     variant, input1, input2, fperrname(excepts));
	if ( (math_errhandling & MATH_ERREXCEPT) && fperr != 0 &&
	     excepts != fperr && !((flags & MF_MAYERR) && !excepts) )
		errx(1, "(%d.) remainderl(%.4Lf, %.4Lf) did not %s",
                     variant, input1, input2, fperrname(fperr));
	if ( !(flags & MF_UNSPEC1) )
	{
		if ( !(isnan(expected) ? isnan(output) :
		       isfinite(expected) && expected != 0.0 ?
		       isfinite(output) && (output == expected || (lower < output && output < upper)) :
		       output == expected) )
		{
			if ( imprecise && isfinite(output) && isfinite(expected) )
				return;
			warnx("(%d.) remainderl(%.4Lf, %.4Lf) = %.17La, not %.17La, diff %.17La, ratio %.20Lg",
			     variant, input1, input2, output, expected,
			     output - expected, output / expected);
			if ( !isfinite(output) || !isfinite(expected) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, 90.01, 13.37, 0, 0, -0xe.51eb851eb846001p-2L, -0xe.51eb851eb846p-2L, -0xe.51eb851eb845fffp-2L, 0);
	test(2, -12.34, 13.37, 0, 0, 0x8.3d70a3d70a3bfffp-3L, 0x8.3d70a3d70a3cp-3L, 0x8.3d70a3d70a3c001p-3L, 0);
	test(3, nanl(""), 13.37, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(4, strtold("inf", NULL), 13.37, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(5, strtold("-inf", NULL), 13.37, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(6, 0.0, 13.37, 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(7, 90.01, -12.34, 0, 0, 0xe.851eb851eb8bfffp-2L, 0xe.851eb851eb8cp-2L, 0xe.851eb851eb8c001p-2L, 0);
	test(8, -12.34, -12.34, 0, 0, -0x0.000000000000001p-16385L, -0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(9, nanl(""), -12.34, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(10, strtold("inf", NULL), -12.34, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(11, strtold("-inf", NULL), -12.34, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(12, 0.0, -12.34, 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(13, 90.01, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(14, -12.34, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(15, nanl(""), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(16, strtold("inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(17, strtold("-inf", NULL), nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(18, 0.0, nanl(""), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(19, 90.01, strtold("inf", NULL), 0, 0, 0xb.4051eb851eb87ffp+3L, 0xb.4051eb851eb88p+3L, 0xb.4051eb851eb8801p+3L, 0);
	test(20, -12.34, strtold("inf", NULL), 0, 0, -0xc.570a3d70a3d7001p+0L, -0xc.570a3d70a3d7p+0L, -0xc.570a3d70a3d6fffp+0L, 0);
	test(21, nanl(""), strtold("inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(22, strtold("inf", NULL), strtold("inf", NULL), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(23, strtold("-inf", NULL), strtold("inf", NULL), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(24, 0.0, strtold("inf", NULL), 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(25, 90.01, strtold("-inf", NULL), 0, 0, 0xb.4051eb851eb87ffp+3L, 0xb.4051eb851eb88p+3L, 0xb.4051eb851eb8801p+3L, 0);
	test(26, -12.34, strtold("-inf", NULL), 0, 0, -0xc.570a3d70a3d7001p+0L, -0xc.570a3d70a3d7p+0L, -0xc.570a3d70a3d6fffp+0L, 0);
	test(27, nanl(""), strtold("-inf", NULL), 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(28, strtold("inf", NULL), strtold("-inf", NULL), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(29, strtold("-inf", NULL), strtold("-inf", NULL), EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(30, 0.0, strtold("-inf", NULL), 0, 0, -0x0.000000000000001p-16385L, 0x0.0p+0L, 0x0.000000000000001p-16385L, 0);
	test(31, 90.01, 0.0, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(32, -12.34, 0.0, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(33, nanl(""), 0.0, 0, 0, nanl(""), nanl(""), nanl(""), 0);
	test(34, strtold("inf", NULL), 0.0, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(35, strtold("-inf", NULL), 0.0, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	test(36, 0.0, 0.0, EDOM, FE_INVALID, nanl(""), nanl(""), nanl(""), 0);
	return imprecise;
}
