/* Test whether a basic remainderf invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)

// Soft fail on rounding errors and report only one.
int imprecise;

static const char* fperrname(int excepts)
{
	switch ( excepts )
	{
	case 0: return "FE_NONE";
	case FE_INVALID: return "FE_INVALID";
	case FE_DIVBYZERO: return "FE_DIVBYZERO";
	case FE_OVERFLOW: return "FE_OVERFLOW";
	case FE_UNDERFLOW: return "FE_UNDERFLOW";
	default: return "FE_MULTIPLE";
	}
}

void test(int variant, float input1, float input2, int errnum, int fperr, float lower, float expected, float upper, int flags)
{
	errno = 0;
	if ( feclearexcept(FE_ALL_EXCEPT) )
		errx(1, "feclearexcept");
	float output = remainderf(input1, input2);
	if ( errnum == 0 && errno )
		err(1, "(%d.) remainderf(%.4f, %.4f) failed",
                    variant, input1, input2);
	if ( (math_errhandling & MATH_ERRNO) && errnum && errno != errnum )
		errx(1, "(%d.) remainderf(%.4f, %.4f) did not %s",
                     variant, input1, input2, strerrno(errnum));
	int excepts = fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
	if ( fperr == 0 && excepts )
		errx(1, "(%d.) remainderf(%.4f, %.4f) %s",
                     variant, input1, input2, fperrname(excepts));
	if ( (math_errhandling & MATH_ERREXCEPT) && fperr != 0 &&
	     excepts != fperr && !((flags & MF_MAYERR) && !excepts) )
		errx(1, "(%d.) remainderf(%.4f, %.4f) did not %s",
                     variant, input1, input2, fperrname(fperr));
	if ( !(flags & MF_UNSPEC1) )
	{
		if ( !(isnan(expected) ? isnan(output) :
		       isfinite(expected) && expected != 0.0 ?
		       isfinite(output) && (output == expected || (lower < output && output < upper)) :
		       output == expected) )
		{
			if ( imprecise && isfinite(output) && isfinite(expected) )
				return;
			warnx("(%d.) remainderf(%.4f, %.4f) = %.6a, not %.6a, diff %.6a, ratio %.8g",
			     variant, input1, input2, output, expected,
			     output - expected, output / expected);
			if ( !isfinite(output) || !isfinite(expected) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, 90.01, 13.37, 0, 0, -0x1.ca3d5ap+1, -0x1.ca3d58p+1, -0x1.ca3d56p+1, 0);
	test(2, -12.34, 13.37, 0, 0, 0x1.07ae0ep+0, 0x1.07ae1p+0, 0x1.07ae12p+0, 0);
	test(3, nanf(""), 13.37, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(4, strtof("inf", NULL), 13.37, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(5, strtof("-inf", NULL), 13.37, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(6, 0.0, 13.37, 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	test(7, 90.01, -12.34, 0, 0, 0x1.d0a3dep+1, 0x1.d0a3ep+1, 0x1.d0a3e2p+1, 0);
	test(8, -12.34, -12.34, 0, 0, -0x1.0p-149, -0x0.0p+0, 0x1.0p-149, 0);
	test(9, nanf(""), -12.34, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(10, strtof("inf", NULL), -12.34, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(11, strtof("-inf", NULL), -12.34, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(12, 0.0, -12.34, 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	test(13, 90.01, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(14, -12.34, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(15, nanf(""), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(16, strtof("inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(17, strtof("-inf", NULL), nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(18, 0.0, nanf(""), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(19, 90.01, strtof("inf", NULL), 0, 0, 0x1.680a3cp+6, 0x1.680a3ep+6, 0x1.680a4p+6, 0);
	test(20, -12.34, strtof("inf", NULL), 0, 0, -0x1.8ae14ap+3, -0x1.8ae148p+3, -0x1.8ae146p+3, 0);
	test(21, nanf(""), strtof("inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(22, strtof("inf", NULL), strtof("inf", NULL), EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(23, strtof("-inf", NULL), strtof("inf", NULL), EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(24, 0.0, strtof("inf", NULL), 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	test(25, 90.01, strtof("-inf", NULL), 0, 0, 0x1.680a3cp+6, 0x1.680a3ep+6, 0x1.680a4p+6, 0);
	test(26, -12.34, strtof("-inf", NULL), 0, 0, -0x1.8ae14ap+3, -0x1.8ae148p+3, -0x1.8ae146p+3, 0);
	test(27, nanf(""), strtof("-inf", NULL), 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(28, strtof("inf", NULL), strtof("-inf", NULL), EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(29, strtof("-inf", NULL), strtof("-inf", NULL), EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(30, 0.0, strtof("-inf", NULL), 0, 0, -0x1.0p-149, 0x0.0p+0, 0x1.0p-149, 0);
	test(31, 90.01, 0.0, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(32, -12.34, 0.0, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(33, nanf(""), 0.0, 0, 0, nanf(""), nanf(""), nanf(""), 0);
	test(34, strtof("inf", NULL), 0.0, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(35, strtof("-inf", NULL), 0.0, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	test(36, 0.0, 0.0, EDOM, FE_INVALID, nanf(""), nanf(""), nanf(""), 0);
	return imprecise;
}
