/*[XSI]*/
/* Test whether a basic yn invocation works. */
/* This test is generated by misc/genbasic.c. */

#include <errno.h>
#include <fenv.h>
#include <math.h>

#include "../basic.h"

#pragma STDC FENV_ACCESS ON

#define MF_UNSPEC1 (1 << 0)
#define MF_UNSPEC2 (1 << 1)
#define MF_MAYERR (1 << 2)

// Soft fail on rounding errors and report only one.
int imprecise;

static const char* fperrname(int excepts)
{
	switch ( excepts )
	{
	case 0: return "FE_NONE";
	case FE_INVALID: return "FE_INVALID";
	case FE_DIVBYZERO: return "FE_DIVBYZERO";
	case FE_OVERFLOW: return "FE_OVERFLOW";
	case FE_UNDERFLOW: return "FE_UNDERFLOW";
	default: return "FE_MULTIPLE";
	}
}

void test(int variant, int input1, double input2, int errnum, int fperr, double lower, double expected, double upper, int flags)
{
	errno = 0;
	if ( feclearexcept(FE_ALL_EXCEPT) )
		errx(1, "feclearexcept");
	double output = yn(input1, input2);
	if ( errnum == 0 && errno )
		err(1, "(%d.) yn(%d, %.4f) failed",
                    variant, input1, input2);
	if ( (math_errhandling & MATH_ERRNO) && errnum && errno != errnum )
		errx(1, "(%d.) yn(%d, %.4f) did not %s",
                     variant, input1, input2, strerrno(errnum));
	int excepts = fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
	if ( fperr == 0 && excepts )
		errx(1, "(%d.) yn(%d, %.4f) %s",
                     variant, input1, input2, fperrname(excepts));
	if ( (math_errhandling & MATH_ERREXCEPT) && fperr != 0 &&
	     excepts != fperr && !((flags & MF_MAYERR) && !excepts) )
		errx(1, "(%d.) yn(%d, %.4f) did not %s",
                     variant, input1, input2, fperrname(fperr));
	if ( !(flags & MF_UNSPEC1) )
	{
		if ( !(isnan(expected) ? isnan(output) :
		       isfinite(expected) && expected != 0.0 ?
		       isfinite(output) && (output == expected || (lower < output && output < upper)) :
		       output == expected) )
		{
			if ( imprecise && isfinite(output) && isfinite(expected) )
				return;
			warnx("(%d.) yn(%d, %.4f) = %.14a, not %.14a, diff %.14a, ratio %.16g",
			     variant, input1, input2, output, expected,
			     output - expected, output / expected);
			if ( !isfinite(output) || !isfinite(expected) )
				exit(1);
			imprecise = 1;
		}
	}
}

int main(void)
{
	test(1, 5, 13.37, 0, 0, -0x1.0d011b95a588cp-3, -0x1.0d011b9599fbp-3, -0x1.0d011b958e6d4p-3, 0);
	test(2, 5, -12.34, EDOM, FE_INVALID, nan(""), nan(""), nan(""), 0 | MF_MAYERR);
	test(3, 5, nan(""), 0, 0, nan(""), nan(""), nan(""), 0);
	test(4, 5, strtod("inf", NULL), 0, 0, -0x0.0000000000001p-1022, 0x0.0p+0, 0x0.0000000000001p-1022, 0);
	test(5, 5, 0.0, ERANGE, FE_DIVBYZERO, strtod("-inf", NULL), strtod("-inf", NULL), strtod("-inf", NULL), 0 | MF_MAYERR);
	return imprecise;
}
