.include "../misc/BSDmakefile.shared"

.PHONY: all
all: test

.PHONY: test
test: $(TEST_RESULTS)

.for TEST in $(TEST_SOURCES)
$(OUT_PATH)/$(TEST:.c=.out): $(TEST)
	../misc/try-compile.sh "$(CC) $(CFLAGS) $(CPPFLAGS)" $(TEST:.c=) "$(LDFLAGS)" "$(EXTRA_LDFLAGS)" "$(OS)" "$(OUT_PATH)"
.endfor

.PHONY: clean
clean: clean-test

.PHONY: clean-test
clean-test:
	rm -rf $(OUT_PATH)
